### ISSUE TITLE
评估数据集

### ISSUE THREAD

**Issue by Tomsentable** [OpenBMB/ToolBench#100]
我似乎没有找到--answer_dir data/answer/toolllama_dfs/G1_instruction这个数据集，您能发一个链接吗

**Comment by pooruss** [comment]
您好，测试数据在[Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J) or [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/f/c9e50625743b40bfbe10/)，根据test_query_ids下的各个测试集的query id，在instruction各个测试集中找到对应测试instances
