### ISSUE TITLE
google下载的数据怎么看，没说明啊

### ISSUE THREAD

**Issue by sunshineflg** [OpenBMB/ToolBench#104]

**Comment by dingguo1996** [comment]
我也有相同的问题。数据下载下来后，我是通过代码脚本查看用到哪些数据来区分它们的用处，希望作者能在这里提供一些指引。

**Comment by pooruss** [comment]
感谢大家提出的问题和建议，先前我们对数据的说明和使用确实不够清晰，目前相关指引已经在readme中更新，希望能帮助到大家更容易上手我们的项目；

欢迎大家继续提出意见和建议，参与我们repo的共建～
