### ISSUE TITLE
我申请了 toolbench key，但是迟迟没有答复

### ISSUE THREAD

**Issue by zzisbeauty** [OpenBMB/ToolBench#105]
- 我试着运行推理的过程（报错），我看到需要填入toolbench key参数，所以大概率是我参数没有输入完整的原因，因此我也已经申请了。但是我迟迟没有收到答复。
- 我一定会在符合要求的范围内使用。 
- 我申请表单填写的邮箱 newswithspring@gmail.com 

- 希望尽快得到表单的答复。 感恩！

**Comment by pooruss** [comment]
您好；关于toolbench key，我们会尽快审核资料进行发放，时间在1小时到2天不等，由此带来的不便敬请谅解～

**Comment by zzisbeauty** [comment]
老师您好，我在您的项目中新增了一个issue，https://github.com/OpenBMB/ToolBench/issues/116



问题我写在了issue中，我想请您百忙之中耽误您几分钟帮我回答一下可以吗？


并非有心麻烦老师，实在是我需要一个完整的逻辑以让我完成代码的debug，进一步明白数据的构成。 感恩！


                       
原始邮件
                       
                     

发件人："Shihao Liang"< ***@***.*** &gt;;

发件时间：2023/9/1 10:17

收件人："OpenBMB/ToolBench"< ***@***.*** &gt;;

抄送人："zzisbeauty"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [OpenBMB/ToolBench] 我申请了 toolbench key，但是迟迟没有答复 (Issue #105)




 
您好；关于toolbench key，我们会尽快审核资料进行发放，时间在1小时到2天不等，由此带来的不便敬请谅解～

**Comment by maoweixiang0823** [comment]
我申请了toolbench key参数一周了还没有发送邮箱是什么问题呢？
