### ISSUE TITLE
测试脚本问题

### ISSUE THREAD

**Issue by gewenbin0992** [OpenBMB/ToolBench#107]
你好，感谢工作。

export OPENAI_KEY=""
export REF_MODEL_DATA="reproduction_data/chatgpt_cot/G1_instruction"
export REF_MODEL_METHOD="CoT"
export TEST_MODEL_DATA="reproduction_data/toolllama_dfs/G1_instruction"
export TEST_MODEL_METHOD="DFS"
python ./toolbench/tooleval/convert_to_answer_format.py \
    --method CoT \
    --answer_dir $REF_MODEL_DATA \
    --output ${REF_MODEL_DATA}_converted

python ./toolbench/tooleval/convert_to_answer_format.py \
    --method DFS \
    --answer_dir $TEST_MODEL_DATA \
    --output ${TEST_MODEL_DATA}_converted

python ./toolbench/tooleval/automatic_eval_sample.py \
    --output ${REF_MODEL_DATA}_converted \
    --ref_output ${TEST_MODEL_DATA}_converted \
    --method $REF_MODEL_METHOD \
    --use_existed_output

以上是README中的Win Rate测试脚本，其中
    --output ${REF_MODEL_DATA}_converted \
    --ref_output ${TEST_MODEL_DATA}_converted \
REF和TEST数据是不是放反了？还是说代码里又改回来了？按照这个脚本测的Win Rate是对的吗？

**Comment by pooruss** [comment]
您好，以上脚本中REF_MODEL是chatgpt_cot，则是评测TEST_MODEL相对于chatgpt_cot的win rate；如果要评测chatgpt_dfs，则把REF_MODEL改成chatgpt_dfs即可

**Comment by gewenbin0992** [comment]
你好，好像没有理解我的意思。麻烦看下下面注释：
python ./toolbench/tooleval/automatic_eval_sample.py
--output ${REF_MODEL_DATA}_converted  # 这一行，应该为 ${TEST_MODEL_DATA}_converted ？
--ref_output ${TEST_MODEL_DATA}_converted # 这一行，应该为 ${REF_MODEL_DATA}_converted ？
--method $REF_MODEL_METHOD
--use_existed_output

**Comment by pooruss** [comment]
噢非常抱歉，这两行的确是放反了，感谢指正！

**Comment by gewenbin0992** [comment]
只是README中的脚本写反了，表格中的数据是没问题的吧？

**Comment by pooruss** [comment]
嗯嗯是的，只是编写readme时的笔误～

**Comment by gewenbin0992** [comment]
好的，谢谢！
