### ISSUE TITLE
diversity_user_prompt

### ISSUE THREAD

**Issue by oaapao** [OpenBMB/ToolBench#111]
作者您好！感谢贵团队的工作！
我想问在构建ToolBench数据集时，在于ChatGPT对话标注生成路径解的时候，diversity_user_prompt被调用的时机是什么？我看到训练数据里有些diversity_user_prompt紧接着user message就被调用了；有的是assistant调用function Call失败了才调用。
以及在inference时，我该在什么时候发送diversity_user_prompt呢？

**Comment by pooruss** [comment]
您好，感谢提出问题～
diversity_user_prompt是在DFS算法中发生节点扩张时被使用的prompt；
这个prompt不需要user在inference过程中来干预，或者说我们（user）已经提前写好了发生节点扩张时prompt的模版，在整个DFS算法的inference中，dfs模型会自主决定需不需要进行节点扩张

**Comment by oaapao** [comment]
感谢贵团队及时的回复！
