### ISSUE TITLE
DFSDT 陷入低效循环和重复

### ISSUE THREAD

**Issue by brianhu2006** [OpenBMB/ToolBench#113]
@pooruss  我们发现，直接使用toollama工具会导致DFST陷入低效循环，浪费时间和资源。例如，我们采用example的例子运行（对应rapidapi有3个），结果发现在运行过程中，每个rapidapi被重复调用了7次

**Comment by pooruss** [comment]
您好，目前放出的toolllama版本确实存在这一缺陷，我们正努力提升toolllama的能力比如提升数据质量、更换更强的基座模型（llama-2）等；
我们也正使用数量更多、质量更高的新版数据（data_0830）对llama-2进行训练，后续将放出更新版本的toolllama-2，敬请期待！

**Comment by brianhu2006** [comment]
@pooruss  估计什么时候可以发布下一个版本的模型？

**Comment by pooruss** [comment]
我们计划在两周内发布下一个版本的模型；
关于DFSDT的讨论和思考可以参考我们论文中的相关部分～
