### ISSUE TITLE
是否在除了llama以外的模型上训练过

### ISSUE THREAD

**Issue by sunshineflg** [OpenBMB/ToolBench#115]
下载的训练集都是英文的，不知道作者训练完成后，有没有在中文上测试效果怎么样？

另外，有没有实验过用国内的LLM，如baichuan, qwen, chatglm 替换llama？

**Comment by pooruss** [comment]
目前尚未在中文上进行测试，我们欢迎大家参与ToolBench的合作共建，比如国内LLM的评测、中文数据生成等～

**Comment by sunshineflg** [comment]
模型训练（不管是全量还是lora）的参数中有model_max_length=8192，但是我们的训练集存在大量长度大于这个数字的。是不是意味着训练的时候很多数据被截断了？

**Comment by sunshineflg** [comment]
另外，https://github.com/OpenBMB/ToolBench/issues/84，是多GPU并行训练的吧，用了几块啊？

**Comment by sunshineflg** [comment]
> 目前尚未在中文上进行测试，我们欢迎大家参与ToolBench的合作共建，比如国内LLM的评测、中文数据生成等～

模型训练（不管是全量还是lora）的参数中有model_max_length=8192，但是toolllama_G123_dfs_train.json中存在大量长度大于这个数字的，是不是意味着训练的时候很多数据被截断了？
另外，https://github.com/OpenBMB/ToolBench/issues/84
是多GPU并行训练的吧，用了几块啊？
