### ISSUE TITLE
答案

### ISSUE THREAD

**Issue by Tomsentable** [OpenBMB/ToolBench#120]
请问ChatGPT-ReACT在默认数据集上生成的答案在哪里，我似乎只看到了chatgpt-dfs的答案

**Comment by pooruss** [comment]
您好，ChatGPT-ReACT的测试集答案在reproduction_data/chatgpt_cot中

**Comment by brianhu2006** [comment]
@pooruss  这个是在云盘的data 文件夹里面吗？ 没有找到这个文件夹reproduction_data/chatgpt_cot，有没有完整路径？

**Comment by Tomsentable** [comment]
我也没有在data中找到reproduction_data/chatgpt_cot

**Comment by pooruss** [comment]
在[google drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)的reproduction_data.zip，下载解压后即可找到

**Comment by Tomsentable** [comment]
Thanks for your reply
