### ISSUE TITLE
0830数据集问题

### ISSUE THREAD

**Issue by JianJianHeng** [OpenBMB/ToolBench#121]
新数据集中的train_messages中的system content中好像只给了工具名称没有工具参数的具体信息。后续有计划像之前那一版一样做一个整合的数据集嘛，像toolllama_G123_dfs-train.json中那样system content中既有工具名称也有工具的参数信息？

非常感谢作者们的工作，对我们特别有用！

**Comment by pooruss** [comment]
您好，在data_0830中是有整合的数据的（toolllama_G123_dfs_train_0830.json），请检查下载的数据是否是最新版本，以及下载过程中是否出现问题～

**Comment by JianJianHeng** [comment]
> 

啊我又下载了一遍发现这回有最新的整合数据了，非常感谢！
