### ISSUE TITLE
ReadME中给出的评估脚本疑似把REF_MODEL与TEST_MODEL写反了

### ISSUE THREAD

**Issue by sjqgogogo** [OpenBMB/ToolBench#122]
`python ./toolbench/tooleval/automatic_eval_sample.py \
    --output ${TEST_MODEL_DATA}_converted \
    --ref_output ${REF_MODEL_DATA}_converted \
    --method $REF_MODEL_METHOD \
    --use_existed_output`

将output与ref_output的值对调后复现出了类似的优胜率，疑似是有个笔误，可以确认下

**Comment by gewenbin0992** [comment]
#107 确实笔误，作者忘记改tooleval里面的readme了

**Comment by pooruss** [comment]
感谢提出问题！tooleval里的readme已更新～
