### ISSUE TITLE
API Server好像又挂了？

### ISSUE THREAD

**Issue by gewenbin0992** [OpenBMB/ToolBench#123]

**Comment by pooruss** [comment]
您好～服务器正在正常运行，可以提供一下case吗

**Comment by gewenbin0992** [comment]
查了下是某些api总是会timeout，比如：

eCommerce-->magic_aliexpress-->api_countriesavailabletoshipping_for_magic_aliexpress
eCommerce-->magic_aliexpress-->api_product_productid_historic_prices_for_magic_aliexpress

**Comment by thuqinyj16** [comment]
部分rapidapi本身服务确实有点问题，这也是各种API Hub的通病，我们觉得让大模型学会处理api call failure是必要的，也符合真实场景～

当然您也可以只对稳定API进行测试～
