### ISSUE TITLE
训练数据-训练成本

### ISSUE THREAD

**Issue by sunshineflg** [OpenBMB/ToolBench#127]
模型训练（不管是全量还是lora）的参数中有model_max_length=8192，但是toolllama_G123_dfs_train.json中大部分数据比8192更长，是不是意味着训练的时候很多数据被截断了？

另外，https://github.com/OpenBMB/ToolBench/issues/84
是多GPU并行训练的吧，用了几块啊？

**Comment by pooruss** [comment]
您好，
1. 训练数据中conversations的每一个列表元素为一个训练instance，超出8192长度的数据占比在5%以下，大部分数据不会超出8192的；
2. 全参数训练和lora都是使用4块

**Comment by thuqinyj16** [comment]
需要超过8192的话可以把position interpolation的ratio开得更高，这样能够轻松支持更长的输入
