### ISSUE TITLE
ArgumentParser in qa_pipeline_open_domain did not have 'api_customization'

### ISSUE THREAD

**Issue by curehabit** [OpenBMB/ToolBench#128]
When run example of "open_domain ", I got this:
`ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py(64)__init__()

-> self.api_customization = args.api_customization

(Pdb)

AttributeError: 'Namespace' object has no attribute 'api_customization'`

**qa_pipeline_open_domain.py** did not have '--api_customization', but  **qa_pipeline.py** has the option '--api_customization'.
It seems like lost one line in **qa_pipeline_open_domain.py**
`parser.add_argument('--api_customization', action="store_true", help="To use customized api or not.")`

**Comment by pooruss** [comment]
Hi, thanks for pointing this out! It has been fixed in the newest code.
