### ISSUE TITLE
toolbench key

### ISSUE THREAD

**Issue by Tomsentable** [OpenBMB/ToolBench#130]
您好，我已经申请了toolbench key还没有审批下来，有没有可用的key供测试用

**Comment by Tomsentable** [comment]
有没有好兄弟分享一下toolbench key 借用一下 我已经申请了，但是还没审批下来

**Comment by pooruss** [comment]
您好，根据https://github.com/OpenBMB/ToolBench#whats-new的讨论，这个issue暂时close了哈

**Comment by pooruss** [comment]
您好，根据https://github.com/OpenBMB/ToolBench/issues/129的讨论，这个issue暂时close了哈
