### ISSUE TITLE
关于论文Table 4实验数据的疑问

### ISSUE THREAD

**Issue by rd-wei** [OpenBMB/ToolBench#131]
感谢你们的工作和分享！

对于你们的研究，我关于论文 “ToolLLM: Facilitating Large Language Models to Master 16000+ Real-world APIs” 的 Table 4 有一个疑问：

如果 **Inst** 是训练集见过的工具，而 **Tool** 和 **Cat** 是没有见过的工具，那么在单工具场景 $I_1$ 中，为什么模型的 pass rate 是在没有见过的工具中更好呢？甚至所有其他没有在 ToolBench 上微调的模型，在 **Inst** 中的 pass rate 也是最低的。不知道你们对于这个问题有没有什么假设或者探索呢？

谢谢你们的解答！

以下是我看到的 Table 4 的截图

![image](https://github.com/OpenBMB/ToolBench/assets/64512950/09072c9e-a54f-4477-96e1-6caa53b37455)

**Comment by pooruss** [comment]
您好，我们认为这个现象是由以下原因导致的：
1. 目前的tooleval中的pass rate指标会受API的稳定性影响
2. 训练工具和测试工具随机划分

训练工具集越大，其包含的不稳定工具就越多，故在指令泛化层面的pass rate也会随之波动甚至降低；比如，给定一个未见过的query和见过的工具集，即使模型已经在这个工具集上训练过，但如果该工具出现了问题导致工具的返回结果异常，那也可能会不passed；

而由于我们对训练和测试工具进行随机划分，可能恰好划分出的测试工具集较稳定，在模型有很好的工具泛化能力基础上加上更稳定的工具，是有可能pass rate更高的

**Comment by rd-wei** [comment]
感谢你们的回答！
所以这个现象可能是由于随机划分的测试工具刚好出现稳定性问题导致的！
