### ISSUE TITLE
关于使用toolllama模型进行推理

### ISSUE THREAD

**Issue by acmisxuyutian** [OpenBMB/ToolBench#132]
![image](https://github.com/OpenBMB/ToolBench/assets/113601978/95e603ad-4bc1-4606-9414-50a86e029407)
请教一下，在利用ToolLLaMA进行推理时，是否有方法能类似GPT-3.5的function_call参数来指定必须调用哪个API。
![image](https://github.com/OpenBMB/ToolBench/assets/113601978/655fe9b6-9443-42fb-959b-d06458398849)

**Comment by thuqinyj16** [comment]
llama本身不支持function call功能，我们通过训练把gpt3.5 function call的能力蒸馏到了llama中。具体而言就是将function call的相关内容flattern成prompt输入给llama，这样它的行为表现本身就和gpt3.5 function call对齐了。只是没有在传参的时候指定这个变量
