### ISSUE TITLE
类别内多工具（intra-category multi-tool instructions）和集合内多工具（intracollection multi-tool instructions）的区别

### ISSUE THREAD

**Issue by wjx2** [OpenBMB/ToolBench#133]
hi，感谢开源了这么棒的工作，没太看懂类别内多工具和集合内多工具的区别是啥，为啥会有这个划分，辛苦帮忙解答下，谢谢。

**Comment by thuqinyj16** [comment]
这个是因为RapidAPI从两种角度对API进行了划分，分别是[category](https://rapidapi.com/categories) 和 [collection](https://rapidapi.com/collections)。具体可以看一下这两个部分的介绍哈

**Comment by wjx2** [comment]
好的，感谢回答～
