### ISSUE TITLE
gpt4结果异常

### ISSUE THREAD

**Issue by wjx2** [OpenBMB/ToolBench#134]
hi，想请教下，我用gpt-4-32k-0613，跑了DFSDT模式的测试集的结果，pass rate avg是56.3，比ChatGPT-DFSDT低，按照我的理解，gpt4的机过应该要比chatgpt高才对，不知道这里面是出了啥问题，请问你们有跑过gpt4的结果吗？谢谢。

**Comment by thuqinyj16** [comment]
我们之前没试过，我们跑一下，一周内反馈给你哈。另外可以麻烦你提供一下gpt-4 eval的结果嘛？我们这里看下是什么问题

**Comment by wjx2** [comment]
58.16 | 70.71 | 76.77 | 43.16 | 47.42 | 41.41|56.3(avg)，和leaderboard的顺序一致

**Comment by pooruss** [comment]
我们已将gpt4结果更新，详见[leaderboard](https://openbmb.github.io/ToolBench/)
