### ISSUE TITLE
关于怎么生成ToolEval的数据集

### ISSUE THREAD

**Issue by huhy-uniplore** [OpenBMB/ToolBench#135]
请问一下作者，这个文件下的数据是怎么生成的呢？相关脚本和过程能否给出？"data/answer/chatgpt_cot/G1_instruction"

**Comment by Bob17293729** [comment]
想借楼问一下，楼主你的chatgpt_cot数据是在哪里获得的？readme提供的清华云盘里只有chatgpt DFS的数据。

**Comment by huhy-uniplore** [comment]
> 想借楼问一下，楼主你的chatgpt_cot数据是在哪里获得的？readme提供的清华云盘里只有chatgpt DFS的数据。

在这里。[reproduction_data.zip](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)

**Comment by huhy-uniplore** [comment]
> > 想借楼问一下，楼主你的chatgpt_cot数据是在哪里获得的？readme提供的清华云盘里只有chatgpt DFS的数据。
> 
> 在这里。[reproduction_data.zip](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)

这是验证的数据集。
