### ISSUE TITLE
How can I solve the following error "ValueError: We need an `offload_dir` to dispatch this model according to this  `device_map`, the following submodules need to be offloaded: "

### ISSUE THREAD

**Issue by xcssgzs** [OpenBMB/ToolBench#14]
Loading checkpoint shards: 100%|██████████| 2/2 [01:50<00:00, 55.30s/it]
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ D:\PycharmProjects\ToolBench\toolbench\inference\inference_single_tool.py:1 │
│ 22 in <module>                                                              │
│                                                                             │
│   119 │   │   # print(output)                                               │
│   120                                                                       │
│   121 if __name__=='__main__':                                              │
│ > 122 │   main()                                                            │
│   123                                                                       │
│                                                                             │
│ D:\PycharmProjects\ToolBench\toolbench\inference\inference_single_tool.py:1 │
│ 12 in main                                                                  │
│                                                                             │
│   109 │   if args.lora_path == "":                                          │
│   110 │   │   customllm = LlamaModel(args.model_path)                       │
│   111 │   else:                                                             │
│ > 112 │   │   customllm = LoraModel(base_name_or_path=args.model_path, mode │
│   113 │   qa =  STQuestionAnswerer(llm_model=customllm)                     │
│   114 │   agent = qa.load_tools(tools_name, tools_config)                   │
│   115                                                                       │
│                                                                             │
│ d:\pycharmprojects\bmtools\bmtools\models\lora_model.py:24 in __init__      │
│                                                                             │
│   21 │   │   │   load_in_8bit=load_8bit,                                    │
│   22 │   │   │   device_map="auto"                                          │
│   23 │   │   )                                                              │
│ > 24 │   │   self.model = PeftModel.from_pretrained(                        │
│   25 │   │   │   model,                                                     │
│   26 │   │   │   model_name_or_path                                         │
│   27 │   │   )                                                              │
│                                                                             │
│ D:\ProgramData\Python\Python39\lib\site-packages\peft\peft_model.py:181 in  │
│ from_pretrained                                                             │
│                                                                             │
│    178 │   │   │   model = cls(model, config, adapter_name)                 │
│    179 │   │   else:                                                        │
│    180 │   │   │   model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_typ │
│ >  181 │   │   model.load_adapter(model_id, adapter_name, **kwargs)         │
│    182 │   │   return model                                                 │
│    183 │                                                                    │
│    184 │   def _setup_prompt_encoder(self, adapter_name):                   │
│                                                                             │
│ D:\ProgramData\Python\Python39\lib\site-packages\peft\peft_model.py:406 in  │
│ load_adapter                                                                │
│                                                                             │
│    403 │   │   │   │   device_map = infer_auto_device_map(                  │
│    404 │   │   │   │   │   self, max_memory=max_memory, no_split_module_cla │
│    405 │   │   │   │   )                                                    │
│ >  406 │   │   │   dispatch_model(                                          │
│    407 │   │   │   │   self,                                                │
│    408 │   │   │   │   device_map=device_map,                               │
│    409 │   │   │   │   offload_dir=offload_dir,                             │
│                                                                             │
│ D:\ProgramData\Python\Python39\lib\site-packages\accelerate\big_modeling.py │
│ :342 in dispatch_model                                                      │
│                                                                             │
│   339 │                                                                     │
│   340 │   disk_modules = [name for name, device in device_map.items() if de │
│   341 │   if offload_dir is None and offload_index is None and len(disk_mod │
│ > 342 │   │   raise ValueError(                                             │
│   343 │   │   │   "We need an `offload_dir` to dispatch this model accordin │
│   344 │   │   │   f"need to be offloaded: {', '.join(disk_modules)}."       │
│   345 │   │   )                                                             │
└─────────────────────────────────────────────────────────────────────────────┘
ValueError: We need an `offload_dir` to dispatch this model according to this 
`device_map`, the following submodules need to be offloaded: 
base_model.model.model.layers.10, base_model.model.model.layers.11, 
base_model.model.model.layers.12, base_model.model.model.layers.13, 
base_model.model.model.layers.14, base_model.model.model.layers.15, 
base_model.model.model.layers.16, base_model.model.model.layers.17, 
base_model.model.model.layers.18, base_model.model.model.layers.19, 
base_model.model.model.layers.20, base_model.model.model.layers.21, 
base_model.model.model.layers.22, base_model.model.model.layers.23, 
base_model.model.model.layers.24, base_model.model.model.layers.25, 
base_model.model.model.layers.26, base_model.model.model.layers.27, 
base_model.model.model.layers.28, base_model.model.model.layers.29, 
base_model.model.model.layers.30, base_model.model.model.layers.31, 
base_model.model.model.norm, base_model.model.lm_head.

**Comment by thuqinyj16** [comment]
Hi, we've updated the codes, please refer to the new one.
