### ISSUE TITLE
Follow-up on Toolbench Key Application for Academic Research

### ISSUE THREAD

**Issue by zhilizju** [OpenBMB/ToolBench#140]
A few days ago, I submitted an application for a Toolbench key, primarily for my academic research purposes. However, I have yet to receive any feedback regarding the status of my application.

Understanding that you may be dealing with numerous requests, I would like to kindly request an update on my application. This key is crucial for my ongoing research, and obtaining it as soon as possible would greatly facilitate my work.

Please let me know if you require any additional information to expedite the approval process. My email address for correspondence is zhili@zju.edu.cn.

Thank you for your attention to this matter. I appreciate your time and assistance.

Best regards,
zhili

**Comment by pooruss** [comment]
Hi, sorry for the late reply to your toolbench key application, we've sent the key. Normally it will take us 2 hours to 2 days to review to the applications, depends on many factors.
