### ISSUE TITLE
机器资源

### ISSUE THREAD

**Issue by syhleo** [OpenBMB/ToolBench#144]
我要使用什么机器资源才能跑起来呀？并且调用我自己的后端API接口，也有100多个接口，我不需要训练，只是想跑起来，看下是否可以实现，AI和自己的产品做交互，用户输入自然语言，进行意图识别，匹配多指令（即：多个API接口)的过程。😀

**Comment by syhleo** [comment]
> 我要使用什么机器资源才能跑起来呀？并且调用我自己的后端API接口，也有100多个接口，我不需要训练，只是想跑起来，看下是否可以实现，AI和自己的产品做交互，用户输入自然语言，进行意图识别，匹配多指令（即：多个API接口)的过程。😀

我这个需要训练么？

**Comment by thuqinyj16** [comment]
不用训练，直接用我们的模型就能泛化过去
