### ISSUE TITLE
Seed examples

### ISSUE THREAD

**Issue by nlpcat** [OpenBMB/ToolBench#145]
In the paper, it mentioned ~50 seed examples for data augmentation generation. May I ask how we can distinguish them from augmented ones? Thanks.

**Comment by thuqinyj16** [comment]
You can find it [here](https://cloud.tsinghua.edu.cn/f/6201d683d1bf42fabf29/?dl=1). Basically you can also just use the augmented ones as seed data, no much difference anyway.
