### ISSUE TITLE
可以用ChatGPT进行open-domain的推理吗

### ISSUE THREAD

**Issue by ZSH-coin** [OpenBMB/ToolBench#148]
你好，我想自己测试一下ChatGPT在不提供api_list的情况下使用工具的性能，但看到qa_pipeline_open_domain.py中parser.add_argument('--model_path', type=str, default="your_model_path/", required=True, help='')这边必须要输入model_path，和qa_pipline.py中不一样，请问目前是不是不支持ChatGPT的open_domian推理，以及如果我想测试一下其他推理链的话，不包含在method中的话我可以怎样在这个代码框架中实现它。

**Comment by pooruss** [comment]
您好，感谢提出问题，chatgpt在open domain setting下性能测试是支持的，先前的代码中的argument设置有误，现已修正；

要实现其他算法的话可以参考https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Algorithms/ 这个目录下的代码
