### ISSUE TITLE
retrieval模型的训练和推理部分，对输入有差异？

### ISSUE THREAD

**Issue by HaoRenkk123** [OpenBMB/ToolBench#149]
训练时，是将ir_corpus(api)的所有信息如category_name，tool_name，api_name，api_description，required_params等等全部文本化送入模型，但是推理脚本inference_eample.py中，model encode只输入了ir_corpus的tool_name和api_name，直接将其经过' '.join文本化送入模型得到encode编码，而不是像训练过程中加入了其他的信息，这样的推理和训练貌似不一致？

**Comment by pooruss** [comment]
您好，training时的corpus建立在这里：https://github.com/OpenBMB/ToolBench/blob/master/toolbench/retrieval/train.py#L77

inference时的corpus建立在这里https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/LLM/retriever.py#L20 ，二者是对齐的
