### ISSUE TITLE
prompt

### ISSUE THREAD

**Issue by Tomsentable** [OpenBMB/ToolBench#15]
Argument `prompt` is expected to be a string. Instead found <class 'list'>.
<img width="606" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/135117887/ceba6abc-7fe1-4eea-acf0-d3264768d625">
when i inference the multi code, the code is strucked at here

**Comment by pooruss** [comment]
We have fixed this bug in the newest version of our codes. Thanks for spotting the issue.
