### ISSUE TITLE
关于实际进行API调用时

### ISSUE THREAD

**Issue by acmisxuyutian** [OpenBMB/ToolBench#150]
您好！想请问一下，你们的大模型在实际进行API调用的过程中是如何保证模型能解析出正确的参数值的，如果错了又是如何进行修正的呢？比如：输入query：帮我预测一下明天北京的天气。API：get_weather（地点：str，日期：date）。那么大模型真的能做到准确的把北京以字符串输入，date以2023-9-17输入吗？地点会不会是输入beijing or BeiJing or Bei_Jing各种形式的北京，date会不会输入的是明天？这样如何提醒大模型进行修正？（我举的例子较简单）

**Comment by pooruss** [comment]
您好，感谢提出问题；一般api会有参数描述，有的会在描述中就指出应该如何正确输入参数；但如果api信息里没有相关的说明，模型会先根据query输入它认为正确的参数，如果输入错误，模型会根据api返回的错误信息修正输入参数

**Comment by acmisxuyutian** [comment]
> 您好，感谢提出问题；一般api会有参数描述，有的会在描述中就指出应该如何正确输入参数；但如果api信息里没有相关的说明，模型会先根据query输入它认为正确的参数，如果输入错误，模型会根据api返回的错误信息修正输入参数

这样的话，我是不是可以认为模型会高度依赖API的质量，包括参数描述的准确性，API返回错误信息的细致程度（如果仅仅是返回类似参数无效这样笼统的错误信息，而不说明哪个参数错误，我认为模型可能很难修正吧）。

**Comment by thuqinyj16** [comment]
高度依赖API的质量是肯定的，无论对人还是对机器来说。即使是高级人类工程师，对一个doc写得稀烂的API应该也很头疼吧[思考]
