### ISSUE TITLE
关于API Retriever

### ISSUE THREAD

**Issue by HeHeYeast** [OpenBMB/ToolBench#151]
不好意思，我想问一下实际使用时API Retriever是怎样使用呢？是将所有API document和指令都分别输入到retriever中计算embedding，然后根据相似度选择前几的API输入给大模型吗？

**Comment by thuqinyj16** [comment]
是的，实际使用的时候API document都是提前算好的，直接load就行。每次只需要算一个指令的embedding，然后算相似度。需要加速的话可以参考meta的faiss

**Comment by HeHeYeast** [comment]
还有请问实际计算时是计算tool的文档的embedding还是计算tool下API的embedding呢

**Comment by Jockzhk** [comment]
> 是的，实际使用的时候API document都是提前算好的，直接load就行。每次只需要算一个指令的embedding，然后算相似度。需要加速的话可以参考meta的faiss

所以准备工作就是装载api文档和大模型生成的指令 然后每一次的使用就是输入一个指令 根据相似度寻找api是吗
