### ISSUE TITLE
请问适合少量API的场景吗

### ISSUE THREAD

**Issue by lllyyyqqq** [OpenBMB/ToolBench#152]
您好，如果只有10到20个API，五个以内的tool，适合从头建数据集以及训练retriever和toolllamma吗？

**Comment by thuqinyj16** [comment]
可以不需要从头构建数据集，直接复用现有数据集训练出来的模型，通过泛化能力直接调用您需要的API

**Comment by lllyyyqqq** [comment]
我做的是中文的，现有的模型可能不太适用，所以想自己弄一个。您这边后面会出面向中文的吗？

**Comment by thuqinyj16** [comment]
会的，一个月左右，同时也欢迎合作共建

**Comment by Jockzhk** [comment]
> 可以不需要从头构建数据集，直接复用现有数据集训练出来的模型，通过泛化能力直接调用您需要的API

那具体需要怎么做呢 将自己的api以及相应的描述文档和对应的gpt生成的指令存起来就行了吗 需要存到哪里呀
