### ISSUE TITLE
bug: Path lost in rapidapi.py in inference_toolllama_pipeline.sh

### ISSUE THREAD

**Issue by zhanghy-sketchzh** [OpenBMB/ToolBench#153]
When I execute inference_toolllama_pipeline.sh, I get an error:
`╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮ │ /cephfs/zhanghongyang/work/ToolBench/toolbench/inference/qa_pipeline.py:31 in <module>           │ │                                                                                                  │ │   28 │   args = parser.parse_args()                                                              │ │   29 │                                                                                           │ │   30 │   pipeline_runner = pipeline_runner(args)                                                 │ │ ❱ 31 │   pipeline_runner.run()                                                                   │ │   32                                                                                             │ │   33                                                                                             │ │                                                                                                  │ │ /cephfs/zhanghongyang/work/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py:551 in run │ │                                                                                                  │ │   548 │   │   │   retriever = None                                                               │ │   549 │   │   for k, task in enumerate(task_list):                                               │ │   550 │   │   │   print(f"process[{self.process_id}] doing task {k}/{len(task_list)}: real_tas   │ │ ❱ 551 │   │   │   result = self.run_single_task(*task, retriever=retriever, process_id=self.pr   │ │   552                                                                                            │ │   553                                                                                            │ │                                                                                                  │ │ /cephfs/zhanghongyang/work/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py:491 in     │ │ run_single_task                                                                                  │ │                                                                                                  │ │   488 │   │   │   if server: print("Warning: no callbacks are defined for server mode")          │ │   489 │   │   │   callbacks = []                                                                 │ │   490 │   │   splits = output_dir_path.split("/")                                                │ │ ❱ 491 │   │   os.makedirs("/".join(splits[:-1]),exist_ok=True)                                   │ │   492 │   │   os.makedirs("/".join(splits),exist_ok=True)                                        │ │   493 │   │   output_file_path = os.path.join(output_dir_path,f"{query_id}_{method}.json")       │ │   494 │   │   if (not server) and os.path.exists(output_file_path):                              │ │                                                                                                  │ │ /cephfs/zhanghongyang/work/miniconda3/envs/llm/lib/python3.10/os.py:225 in makedirs              │ │                                                                                                  │ │    222 │   │   if tail == cdir:           # xxx/newdir/. exists if xxx/newdir exists             │ │    223 │   │   │   return                                                                        │ │    224 │   try:                                                                                  │ │ ❱  225 │   │   mkdir(name, mode)                                                                 │ │    226 │   except OSError:                                                                       │ │    227 │   │   # Cannot rely on checking for EEXIST, since the operating system                  │ │    228 │   │   # could give priority to other errors like EACCES or EROFS                        │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ FileNotFoundError: [Errno 2] No such file or directory: ''`

solution： remove the `OS makedirs ("/". The join (splits] [: - 1), exist_ok = True)`

**Comment by thuqinyj16** [comment]
Thanks for pointing this out!

**Comment by AL-377** [comment]
So is it fixed now?It seems to remain still
