### ISSUE TITLE
使用llama2 使用 toolbench训练代码。pass-rate 复现不出 paper的值。

### ISSUE THREAD

**Issue by xxzcc** [OpenBMB/ToolBench#155]
使用如下脚本：(基本同官方给的例子）
'''
export PYTHONPATH=./
torchrun --nproc_per_node=2 --master_port=20001 toolbench/train/train_mem.py \
    --model_name_or_path huggyllama/llama2-7b  \
    --data_path  data/toolllama_G123_dfs_train.json \
    --eval_data_path  data/toolllama_G123_dfs_eval.json \
    --conv_template tool-llama-single-round \
    --bf16 True \
    --output_dir toolllama \
    --num_train_epochs 2 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "epoch" \
    --prediction_loss_only \
    --save_strategy "steps" \
    --save_steps 200 \
    --save_total_limit 8 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.04 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --tf32 True \
    --source_model_max_length 2048 \
    --model_max_length 8192 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --report_to none
'''
base模型使用llama2-7b ，然后跑完测试文件 toolllama 里面的模型，结果 I1-Tool pass-rate 分数是 64分，但是论文 I1-Tool pass-rate 分数是80，如下。
![image](https://github.com/OpenBMB/ToolBench/assets/20204693/3c0c7e4b-5ac1-4a18-a4e5-790ff379c265)

当我使用 论文 release 的 tool-llama-7b 模型进行推理，生成 answer, 再使用 pass_rate 测试，跑分78分，说明 infer 代码/流程 基本没有问题。

请问： 使用以上脚本进行训练，分数仅64分的原因是？  求助！感谢！

**Comment by zhanghy-sketchzh** [comment]
你好，请问你在推理的时候会出现显存oom吗

**Comment by xxzcc** [comment]
> 你好，请问你在推理的时候会出现显存oom吗

不会。
> 结果 I1-Tool pass-rate 分数是 64分，但是论文 I1-Tool pass-rate 分数是80，如下。
使用的和官方一样的A100 80G显存， max_seq_len=8192。 测试/推理正常。
![image](https://github.com/OpenBMB/ToolBench/assets/20204693/3db5336a-2158-45b9-af2c-e27ef3703745)

**Comment by zhanghy-sketchzh** [comment]
我按照官方的lora方法微调llama7b，用ToolBench/data/test_query_ids/G1_instruction_test_query_ids.json中对应的query推理，pass-rate分数是61，还高了不少。但是我单卡A100(40G)在推理的时候显存会oom，全量微调也不行，只能用lora版本了，不知道有没有人和我一样的情况

**Comment by xxzcc** [comment]
> 我按照官方的lora方法微调llama7b，用ToolBench/data/test_query_ids/G1_instruction_test_query_ids.json中对应的query推理，pass-rate分数是61
这个论文pass-rate是多少分？ 或者说 官方 release toollama-7b 是多少分。
> 还高了不少 
这个结论怎么来的？
![image](https://github.com/OpenBMB/ToolBench/assets/20204693/79927211-f6e2-4a68-9e7c-433bc4ff6619)
看论文的 I1-Inst 的pass 是 68分啊！
单卡A100（40G）推理 7B 会OOM吗？讲道理，你可以训练起来，没有道理推理OOM，训练不OOM。

**Comment by zhanghy-sketchzh** [comment]
> > 我按照官方的lora方法微调llama7b，用ToolBench/data/test_query_ids/G1_instruction_test_query_ids.json中对应的query推理，pass-rate分数是61
> 
> 这个论文pass-rate是多少分？ 或者说 官方 release toollama-7b 是多少分。
> 论文pass-rate是51，我是用的lora微调，分要低一点

> > 还高了不少
> 
> 这个结论怎么来的？ ![image](https://user-images.githubusercontent.com/20204693/269525182-79927211-f6e2-4a68-9e7c-433bc4ff6619.png) 看论文的 I1-Inst 的pass 是 68分啊！ 单卡A100（40G）推理 7B 会OOM吗？讲道理，你可以训练起来，没有道理推理OOM，训练不OOM。

我是lora推理微调，量化了的

**Comment by liujiaheng** [comment]
@thuqinyj16 Hi, I have met similar problems, where the reproduction results are lower than the results reported in your paper. Could you provide some suggestions or strategies to improve the results better?

Thanks,
Jiaheng.

**Comment by realgump** [comment]
你好，我也遇到了类似的问题，pass rate要比论文汇报的低很多。另外你是否测试了win rate？win rate似乎也无法复现。

**Comment by thuqinyj16** [comment]
您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048

另外我理解楼上的同学应该都是自己训练llama-2发现有问题对吧？有同学（1）训练llama-1出问题或者（2）用我们提供的llama出问题的吗？

**Comment by thuqinyj16** [comment]
另外麻烦发一下觉得有问题的llama-2在测试集上的输出哈，我们看一下结果是否有问题

**Comment by pooruss** [comment]
> 使用如下脚本：(基本同官方给的例子） ''' export PYTHONPATH=./ torchrun --nproc_per_node=2 --master_port=20001 toolbench/train/train_mem.py --model_name_or_path huggyllama/llama2-7b --data_path data/toolllama_G123_dfs_train.json --eval_data_path data/toolllama_G123_dfs_eval.json --conv_template tool-llama-single-round --bf16 True --output_dir toolllama --num_train_epochs 2 --per_device_train_batch_size 2 --per_device_eval_batch_size 2 --gradient_accumulation_steps 8 --evaluation_strategy "epoch" --prediction_loss_only --save_strategy "steps" --save_steps 200 --save_total_limit 8 --learning_rate 5e-5 --weight_decay 0. --warmup_ratio 0.04 --lr_scheduler_type "cosine" --logging_steps 1 --fsdp "full_shard auto_wrap" --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' --tf32 True --source_model_max_length 2048 --model_max_length 8192 --gradient_checkpointing True --lazy_preprocess True --report_to none ''' base模型使用llama2-7b ，然后跑完测试文件 toolllama 里面的模型，结果 I1-Tool pass-rate 分数是 64分，但是论文 I1-Tool pass-rate 分数是80，如下。 ![image](https://user-images.githubusercontent.com/20204693/269238436-3c0c7e4b-5ac1-4a18-a4e5-790ff379c265.png)
> 
> 当我使用 论文 release 的 tool-llama-7b 模型进行推理，生成 answer, 再使用 pass_rate 测试，跑分78分，说明 infer 代码/流程 基本没有问题。
> 
> 请问： 使用以上脚本进行训练，分数仅64分的原因是？ 求助！感谢！

您好，因为了llama2的sequence length是4096，所以用llama2训练时interpolation ratio=8192/4096=2，但这里脚本里source_model_max_length设置的是2048，所以interpolation ratio会被算成4（8192/2048=4），需要把source_model_max_length改为4096哈

**Comment by zhanghy-sketchzh** [comment]
> 您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048
> 
> 另外我理解楼上的同学应该都是自己训练llama-2发现有问题对吧？有同学（1）训练llama-1出问题或者（2）用我们提供的llama出问题的吗？
llama-1是从[huggyllama/llama-7b](https://huggingface.co/huggyllama/llama-7b)这里下载吗，为什么这个和toolllama两者的config差异这么大

**Comment by realgump** [comment]
> 您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048

感谢回复。确实应该是这个问题，我使用的是9月前的版本，还没有source_model_max_length这个参数，训练llama2使用了默认的interpolation。

**Comment by xxzcc** [comment]
> 您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048
> 
> 另外我理解楼上的同学应该都是自己训练llama-2发现有问题对吧？有同学（1）训练llama-1出问题或者（2）用我们提供的llama出问题的吗？

llama2_7b_base 的 config.json如下。
‘’‘
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.31.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}
’‘’

使用 llama2-7b 的 source_model_max_length=2048 和 4096 我均尝试过。I1-Tool pass rate 均是60多， 前者64，后者61分。

1. llama2-7b_base作为baseline 训练的训练日志如下 （source_model_max_length=2048 ）：
[train_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log](https://github.com/OpenBMB/ToolBench/files/12705352/train_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log)
inferece 日志为
[inference_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log](https://github.com/OpenBMB/ToolBench/files/12705357/inference_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log)
answer 的日志为：
[llama2_7b_sft.zip](https://github.com/OpenBMB/ToolBench/files/12705362/llama2_7b_sft.zip)
最终计算I1-Tool pass rate 为 64分

2. llama2-7b_base作为baseline 训练的训练日志如下 （source_model_max_length=4096 ）：
训练日志：
[train_llama2_7b_sft_4096.log](https://github.com/OpenBMB/ToolBench/files/12705364/train_llama2_7b_sft_4096.log)
推理日志：
[llama2_7b_sft_4096.log](https://github.com/OpenBMB/ToolBench/files/12705370/llama2_7b_sft_4096.log)
answer 的日志为：
[llama2_7b_sft_4096.zip](https://github.com/OpenBMB/ToolBench/files/12705371/llama2_7b_sft_4096.zip)
最终计算I1-Tool pass rate 为61分

-------------------
上面的 1，2 证明不论使用 source_model_max_length = 2048 | 4096，效果差不多。
有两个diff 点。 
diff 点 1: 我的训练 global_bs=bs_per_gpu * ga * gpu = 2*8*8=128， 比官方例子大，后面我降低ga，将global_bs变成 32 = bs_per_gpu * ga * gpu = 2 * 4 * 4; 后，实验分数55分。
diff 点 2: 上面实验2， 训练的时候 replace_llama_with_condense(ratio=2)， 但是infer的时候写死:
 replace_llama_with_condense(ratio=4) (代码见：
https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L405 ）
这么测试肯定不科学。
然后我拿13b的模型测试了一下ratio 对 infer的影响。 结果如下。 （为什么没用实验2做该分析，因为资源不足，时间不足，ckpt被清了）
![image](https://github.com/OpenBMB/ToolBench/assets/20204693/17be4a28-806e-417c-98c8-37bcc29d49c1)

**Comment by xxzcc** [comment]
@pooruss @thuqinyj16  如上。辛苦两位不忙的时候看一下。

**Comment by xxzcc** [comment]
> > 您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048
> > 另外我理解楼上的同学应该都是自己训练llama-2发现有问题对吧？有同学（1）训练llama-1出问题或者（2）用我们提供的llama出问题的吗？

再补充一个新实验。 使用 llama_7b_base 进行训练。结果是I1-tool 分数是43.  global_bs和提供的训练代码一致。论文分数是80分。

训练脚本：
[train_llama1_7b.log](https://github.com/OpenBMB/ToolBench/files/12705719/train_llama1_7b.log)
训练日志：
[train_llama1_7b_bs32.log](https://github.com/OpenBMB/ToolBench/files/12705720/train_llama1_7b_bs32.log)
inference 日志：
[inference_llama_7b_sft_8192_bs32.log](https://github.com/OpenBMB/ToolBench/files/12705721/inference_llama_7b_sft_8192_bs32.log)
ans结果日志:
[llama_7b_sft_zcc_s_2048_d_8192_bs32.zip](https://github.com/OpenBMB/ToolBench/files/12705722/llama_7b_sft_zcc_s_2048_d_8192_bs32.zip)


麻烦帮忙看一下。

**Comment by thuqinyj16** [comment]
> 我按照官方的lora方法微调llama7b，用ToolBench/data/test_query_ids/G1_instruction_test_query_ids.json中对应的query推理，pass-rate分数是61，还高了不少。但是我单卡A100(40G)在推理的时候显存会oom，全量微调也不行，只能用lora版本了，不知道有没有人和我一样的情况

推理的时候无论是用lora还是全参数的版本对显存的消耗应该是一样的吧？

**Comment by thuqinyj16** [comment]
> @thuqinyj16 Hi, I have met similar problems, where the reproduction results are lower than the results reported in your paper. Could you provide some suggestions or strategies to improve the results better?
> 
> Thanks, Jiaheng.

Hi, can you also report your testing results using ChatGPT or our provided ToolLLaMA? We're trying to locate your problem, i.e., whether the model-side or the toolserver-side.

**Comment by thuqinyj16** [comment]
> 你好，我也遇到了类似的问题，pass rate要比论文汇报的低很多。另外你是否测试了win rate？win rate似乎也无法复现。

你好，请问可以同时测一下用chatgpt或我们提供的toolllama的结果嘛？我们需要确认一下你的问题是模型导致的还是rapidapi server导致的

**Comment by thuqinyj16** [comment]
> > 您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048
> > 另外我理解楼上的同学应该都是自己训练llama-2发现有问题对吧？有同学（1）训练llama-1出问题或者（2）用我们提供的llama出问题的吗？
> 
> llama2_7b_base 的 config.json如下。 ‘’‘ { "architectures": [ "LlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 2048, "model_type": "llama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": null, "tie_word_embeddings": false, "torch_dtype": "float16", "transformers_version": "4.31.0.dev0", "use_cache": true, "vocab_size": 32000 } ’‘’
> 
> 使用 llama2-7b 的 source_model_max_length=2048 和 4096 我均尝试过。I1-Tool pass rate 均是60多， 前者64，后者61分。
> 
> 1. llama2-7b_base作为baseline 训练的训练日志如下 （source_model_max_length=2048 ）：
>    [train_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log](https://github.com/OpenBMB/ToolBench/files/12705352/train_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log)
>    inferece 日志为
>    [inference_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log](https://github.com/OpenBMB/ToolBench/files/12705357/inference_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log)
>    answer 的日志为：
>    [llama2_7b_sft.zip](https://github.com/OpenBMB/ToolBench/files/12705362/llama2_7b_sft.zip)
>    最终计算I1-Tool pass rate 为 64分
> 2. llama2-7b_base作为baseline 训练的训练日志如下 （source_model_max_length=4096 ）：
>    训练日志：
>    [train_llama2_7b_sft_4096.log](https://github.com/OpenBMB/ToolBench/files/12705364/train_llama2_7b_sft_4096.log)
>    推理日志：
>    [llama2_7b_sft_4096.log](https://github.com/OpenBMB/ToolBench/files/12705370/llama2_7b_sft_4096.log)
>    answer 的日志为：
>    [llama2_7b_sft_4096.zip](https://github.com/OpenBMB/ToolBench/files/12705371/llama2_7b_sft_4096.zip)
>    最终计算I1-Tool pass rate 为61分
> 
> 上面的 1，2 证明不论使用 source_model_max_length = 2048 | 4096，效果差不多。 有两个diff 点。 diff 点 1: 我的训练 global_bs=bs_per_gpu * ga * gpu = 2_8_8=128， 比官方例子大，后面我降低ga，将global_bs变成 32 = bs_per_gpu * ga * gpu = 2 * 4 * 4; 后，实验分数55分。 diff 点 2: 上面实验2， 训练的时候 replace_llama_with_condense(ratio=2)， 但是infer的时候写死: replace_llama_with_condense(ratio=4) (代码见： https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L405 ） 这么测试肯定不科学。 然后我拿13b的模型测试了一下ratio 对 infer的影响。 结果如下。 （为什么没用实验2做该分析，因为资源不足，时间不足，ckpt被清了） ![image](https://user-images.githubusercontent.com/20204693/270081588-17be4a28-806e-417c-98c8-37bcc29d49c1.png)

您好，可以测试一下我们最新提供的120000条数据的结果嘛？以及您本地用llama-1训练后测试的效果如何

**Comment by xxzcc** [comment]
> > > 您好，请问可以发一下toolllama-2里的config.json内容吗？我们怀疑可能跟interpolation的ratio有关，代码里是默认扩充四倍的，而llama-2的seq len本身是4096，非llama-1的2048
> > > 另外我理解楼上的同学应该都是自己训练llama-2发现有问题对吧？有同学（1）训练llama-1出问题或者（2）用我们提供的llama出问题的吗？
> > 
> > 
> > llama2_7b_base 的 config.json如下。 ‘’‘ { "architectures": [ "LlamaForCausalLM" ], "bos_token_id": 1, "eos_token_id": 2, "hidden_act": "silu", "hidden_size": 4096, "initializer_range": 0.02, "intermediate_size": 11008, "max_position_embeddings": 2048, "model_type": "llama", "num_attention_heads": 32, "num_hidden_layers": 32, "num_key_value_heads": 32, "pad_token_id": 0, "pretraining_tp": 1, "rms_norm_eps": 1e-05, "rope_scaling": null, "tie_word_embeddings": false, "torch_dtype": "float16", "transformers_version": "4.31.0.dev0", "use_cache": true, "vocab_size": 32000 } ’‘’
> > 使用 llama2-7b 的 source_model_max_length=2048 和 4096 我均尝试过。I1-Tool pass rate 均是60多， 前者64，后者61分。
> > 
> > 1. llama2-7b_base作为baseline 训练的训练日志如下 （source_model_max_length=2048 ）：
> >    [train_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log](https://github.com/OpenBMB/ToolBench/files/12705352/train_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log)
> >    inferece 日志为
> >    [inference_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log](https://github.com/OpenBMB/ToolBench/files/12705357/inference_llama_2b_7b_toolbench_sft_source_2048_l1_tool_64.log)
> >    answer 的日志为：
> >    [llama2_7b_sft.zip](https://github.com/OpenBMB/ToolBench/files/12705362/llama2_7b_sft.zip)
> >    最终计算I1-Tool pass rate 为 64分
> > 2. llama2-7b_base作为baseline 训练的训练日志如下 （source_model_max_length=4096 ）：
> >    训练日志：
> >    [train_llama2_7b_sft_4096.log](https://github.com/OpenBMB/ToolBench/files/12705364/train_llama2_7b_sft_4096.log)
> >    推理日志：
> >    [llama2_7b_sft_4096.log](https://github.com/OpenBMB/ToolBench/files/12705370/llama2_7b_sft_4096.log)
> >    answer 的日志为：
> >    [llama2_7b_sft_4096.zip](https://github.com/OpenBMB/ToolBench/files/12705371/llama2_7b_sft_4096.zip)
> >    最终计算I1-Tool pass rate 为61分
> > 
> > 上面的 1，2 证明不论使用 source_model_max_length = 2048 | 4096，效果差不多。 有两个diff 点。 diff 点 1: 我的训练 global_bs=bs_per_gpu * ga * gpu = 2_8_8=128， 比官方例子大，后面我降低ga，将global_bs变成 32 = bs_per_gpu * ga * gpu = 2 * 4 * 4; 后，实验分数55分。 diff 点 2: 上面实验2， 训练的时候 replace_llama_with_condense(ratio=2)， 但是infer的时候写死: replace_llama_with_condense(ratio=4) (代码见： https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L405 ） 这么测试肯定不科学。 然后我拿13b的模型测试了一下ratio 对 infer的影响。 结果如下。 （为什么没用实验2做该分析，因为资源不足，时间不足，ckpt被清了） ![image](https://user-images.githubusercontent.com/20204693/270081588-17be4a28-806e-417c-98c8-37bcc29d49c1.png)
> 
> 您好，可以测试一下我们最新提供的120000条数据的结果嘛？以及您本地用llama-1训练后测试的效果如何

是说用这个数据集进行训练后的测试结果吗？（这个数据集比之前大很多，我可能需要更多的训练时间）｜ （我测试过使用 llama-2-7b 作为 base 然后 Source_len=2048, model_len=8192 ，训练一半这个数据集的ckpt，I1-tool 测试分数是63分(虽然只训练了一半，但是这时候的训练数据其实已经 > 0830之前的数据了)，和0830前的数据训练完的分数差不多。 也许训练完分数更高，但是还没有尝试。）你们有使用新数据集后 I1-tool 分数会更高吗？ （我下周试一试重新拉最新的代码跑一版试试！十分感谢回复！）

**Comment by liujiaheng** [comment]
@thuqinyj16 使用微信联系如何？我发邮件过去了

**Comment by Woooooody** [comment]
@thuqinyj16  你好，我在实验过程中也遇到了类似问题，使用同样的模型和release的数据集重新训练，但是无法复现结果。

**Comment by pooruss** [comment]
我们已经发布了新版的tooleval和该版本tooleval的所有模型结果，较之前版本tooleval会更加稳定易于复现。

注：需使用最新release的[模型](https://huggingface.co/ToolBench/ToolLLaMA-2-7b-v2)和新的[测试数据](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J) (在data/test_instruction中)
