### ISSUE TITLE
in-context DFSDT

### ISSUE THREAD

**Issue by Daisy5296** [OpenBMB/ToolBench#159]
请问是否可以不训练tool data，直接基于原始llama chat模型进行few shot的DFSDT推理，实现工具调用？效果如何？

**Comment by thuqinyj16** [comment]
可以的。我们论文中的实验只做过泛化实验 (out-of-distribution generalization)，即模型永远只去学习使用没有见过的工具，效果很好

**Comment by Daisy5296** [comment]
我的意思是，基于原始的Llama模型，而不是toolLLama :) 通过in-context learning而不是finetune。不知是否可行呢..?

**Comment by thuqinyj16** [comment]
可能不太行，我估计只有llama-2的30B以上的chat模型能看出tool learning场景下的in-context能力

**Comment by Daisy5296** [comment]
好的 谢谢~！
