### ISSUE TITLE
使用其他模型做评测的步骤

### ISSUE THREAD

**Issue by wildwind0** [OpenBMB/ToolBench#160]
你好，如果我要用ToolBench的数据集评测自己的模型，我要怎么做呢？README里写感觉不是明确，我理解一下是否是这样的：

1. 在toolbench/inference/LLM中定义自己的模型，包括其他模型类里的五个方法：add_message，change_message，display_conversation，parse和prediction
2. 然后运行`toolbench/inference/qa_pipeline.py`，input_query_file使用测试集的instruction，模型选自己的，这样就得到测试集即榜单的结果数据
3. 运行convert_to_answer_format.py和automatic_eval_sample.py去获取优胜率 ，运行pass_rate.py去获取通过率

以上流程是对的吗？主要疑问是模型定义那块几个函数的定义有什么要求呢？

**Comment by thuqinyj16** [comment]
以上流程没问题，另外如果您考虑做open-domain的setting的话（就是API需要先retrieve），就是用https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/qa_pipeline_open_domain.py这个哈

**Comment by wildwind0** [comment]
谢谢解答，请问定义模型那块的五个函数，特别是parse函数具体用途是什么？我需要怎么去定义呢

**Comment by thuqinyj16** [comment]
您好，parse的作用就是得到模型的输出。不同模型的交互逻辑不一样，比如有的用function call，有的就是纯prompt然后在content里生成。总之选择一个适合你的方案即可
