### ISSUE TITLE
Crawling RapidAPI

### ISSUE THREAD

**Issue by sandeepsundaram** [OpenBMB/ToolBench#161]
Please can you share the method used to crawl RapidAPI to generate G1_query.json? Where can I find the source code?

**Comment by thuqinyj16** [comment]
Hi, sorry but we cannot provide the crawling codes for RapidAPI due to their license-related issue. But we have provided all the crawled data on RapidAPI.

**Comment by thuqinyj16** [comment]
For instruction generation, you can refer to the codes [here](https://cloud.tsinghua.edu.cn/f/57b7c6cc52fe4426b68c/?dl=1)
