### ISSUE TITLE
关于人工交叉标注数据集

### ISSUE THREAD

**Issue by hanqichen** [OpenBMB/ToolBench#163]
在 tooleval 中看到有一个[人类交叉标注数据集](https://github.com/OpenBMB/ToolBench/blob/master/toolbench/tooleval/README_ZH.md#%E4%BA%BA%E7%B1%BB%E4%BA%A4%E5%8F%89%E6%A0%87%E6%B3%A8%E6%95%B0%E6%8D%AE%E9%9B%86)，但在所下载的数据中，没有看到类似human_cross_annotated_data.json的文件。

请问这个数据集应该从哪里获取？

**Comment by pooruss** [comment]
在最新的[Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)上的reproduction_data里可以找到
