### ISSUE TITLE
执行davinci模型的时候，缺少了初始Prompt

### ISSUE THREAD

**Issue by wildwind0** [OpenBMB/ToolBench#172]
single_chain里的do_chain函数里，定义了start_message_list，system是FORMAT_INSTRUCTIONS_SYSTEM_FUNCTION，user是FORMAT_INSTRUCTIONS_USER_FUNCTION，但在执行模型davinci（即text-davinci-003）prediction过程的时候，会调用parse函数，实际上do_chain里的FORMAT_INSTRUCTIONS_SYSTEM_FUNCTION并没有被包含在最终发给模型的prompt里。

但执行chatgpt_function时，因为是直接把conversation_history给到了请求模型的json体里，所以包含了最初的FORMAT_INSTRUCTIONS_SYSTEM_FUNCTION prompt。

davinci少了FORMAT_INSTRUCTIONS_SYSTEM_FUNCTION这个初始prompt会比较影响评估结果吧？

**Comment by pooruss** [comment]
目前我们的prompt大概可以分为两种，一种是给有function call功能的LLM，一种是给没有function call功能的LLM，davinci属于后者，给davinci的prompt是FORMAT_INSTRUCTIONS_SYSTEM_FUNCTION_ZEROSHOT
