### ISSUE TITLE
计算win rate的时候会把node.message截断到100个字符，不会影响Evaluator判定answer是否解决吗？

### ISSUE THREAD

**Issue by wildwind0** [OpenBMB/ToolBench#181]
代码位置: ToolBench/toolbench/tooleval/evaluation/dataclass.py
![image](https://github.com/OpenBMB/ToolBench/assets/25784304/6e82de98-85a7-4f0f-9723-f1f13a625899)

造成最后的answer不完整：
![image](https://github.com/OpenBMB/ToolBench/assets/25784304/3b708c51-e4cd-4ebf-9a4d-c96038bfd73d)

对于给了final_awswer的样本，会让Evaluator去评估，即`evaluator.check_is_solved`函数。所以，计算win rate的时候，如果在`convert_to_answer_format`过程中，把node.message截断到100个字符，造成final_answer不完整，难道不会影响Evaluator判定answer是否解决吗？

**Comment by pooruss** [comment]
Hi, 感谢提出问题，此部分代码为旧版本tooleval，此前新版tooleval更新的时候遗漏了，目前已经最新的代码更新，不再是截断到100字符
