### ISSUE TITLE
Possible bug in toolbench.retrieval.api_evaluator.compute_ndcg_for_query

### ISSUE THREAD

**Issue by parth-jaggi-wd** [OpenBMB/ToolBench#184]
Following is the code for `compute_ndcg_for_query` taken from `toolbench.retrieval.api_evaluator`:

```
def compute_ndcg_for_query(query_tuple):
    query_itr, query_id, top_hits, relevant_docs, corpus_ids, k = query_tuple
    query_relevant_docs = relevant_docs[query_id]

    # Build the ground truth relevance scores and the model's predicted scores
    true_relevance = np.zeros(len(corpus_ids))
    predicted_scores = np.zeros(len(corpus_ids))

    for hit in top_hits[:k]: # Limit to top k results
        predicted_scores[corpus_ids.index(hit['corpus_id'])] = hit['score']
        if hit['corpus_id'] in query_relevant_docs:
            true_relevance[corpus_ids.index(hit['corpus_id'])] = 1

    return ndcg_score([true_relevance], [predicted_scores])
```

Why is true_relevance based on if hit['corpus_id'] is in query_relevant_docs?
true_relevance should only be based on query_relevant_docs as per my understanding of Ideal DCG.

The example given in [NDCG - Wikipedia](https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Normalized_DCG:~:text=In%20addition%20to,ideal%20ordering%20is%3A) also shows the same:
D_7 and D_8 documents aren't retrieved but are still used for calculated the Ideal DCG.

**Comment by parth-jaggi-wd** [comment]
Also `ndcg_score` call should be with k parameter:
`ndcg_score([true_relevance], [predicted_scores], k=3)`

**Comment by Kunlun-Zhu** [comment]
Thanks for clarify the ndcg_score missing the parameter 'k';  we'll fix this in the next release.

**Comment by Kunlun-Zhu** [comment]
However, we do implement the ndcg-k whin this function directly which makes it seem confusing to you, we'll also fix this in the next update.

**Comment by Kunlun-Zhu** [comment]
The latest version of ndcg function has been committed.

**Comment by Reason-Wang** [comment]
The problem seems still there: https://github.com/OpenBMB/ToolBench/blob/5b5debedaf8b165ed5ecc30b210423e33f466870/toolbench/retrieval/api_evaluator.py#L52

How does this effects the results?
