### ISSUE TITLE
如何订阅rapidapi以及获取预测结果？

### ISSUE THREAD

**Issue by lightislost** [OpenBMB/ToolBench#194]
你好，我想基于toolbench这个框架来评测私人模型的工具能力。但是有一个问题，里面涉及到大类rapidapi，这部分只能由我这边先对toolbench中涉及到api进行订阅后才可以实现预测过程么？是否其它推荐的方式可以实现这个预测过程？

**Comment by pooruss** [comment]
您好，我们提供RapidAPI后端服务，使您无需使用自己的RapidAPI密钥和订阅API。请填写我们的[表格](https://forms.gle/oCHHc8DQzhGfiT9r6)，我们将尽快对其进行审核并向您发送 ToolBench 密钥以开始使用

**Comment by lightislost** [comment]
感谢您的快速回复，我已经提交申请
