### ISSUE TITLE
ModuleNotFoundError: No module named 'toolbench'

### ISSUE THREAD

**Issue by ShubhamVerma16** [OpenBMB/ToolBench#195]
Hi, 
I have been trying to run the inference through qa_pipeline  in the repo after cloning it and it throws the following error.
Command:
` python toolbench/inference/qa_pipeline.py --tool_root_dir data/toolenv/tools/ --backbone_model toolllama --model_path ToolBench/ToolLLaMA-7b --max_observation_length 1024 --observ_compress_method truncate --method DFS_woFilter_w2 --input_query_file data/test_instruction/G1_instruction.json --output_answer_file toolllama_dfs_inference_result --toolbench_key $toolbench_key`
Error:
`ModuleNotFoundError: No module named 'toolbench'`

Can you please help me with the issue.
Thanks.

**Comment by pooruss** [comment]
Hi, you can set the PYTHONPATH to your ToolBench path before you run the inference to solve this.
