### ISSUE TITLE
how can i get the toolllama train data?

### ISSUE THREAD

**Issue by Aran-Guo** [OpenBMB/ToolBench#196]

**Comment by pooruss** [comment]
Hi, please download our dataset using the following link: [Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J) or [Tsinghua Cloud](https://cloud.tsinghua.edu.cn/f/c9e50625743b40bfbe10/). More details about the data can be found in the readme.
