### ISSUE TITLE
Performance of GPT3.5/4 on the benchmark?

### ISSUE THREAD

**Issue by JianxinMa** [OpenBMB/ToolBench#20]
The table displays the performance of cpmbee, llama, and vicuna, but it doesn't seem to include information about GPT3.5/4. How well do GPT3.5 and GPT4 perform on this benchmark?

**Comment by thuqinyj16** [comment]
Yes, we'll soon update the results of GPT3.5 and GPT4. Thanks for reminding. Finetuned LLaMA performs similar to GPT3.5, but only have ~85% performance of GPT4.
