### ISSUE TITLE
ToolBench api申请

### ISSUE THREAD

**Issue by xinyiqin** [OpenBMB/ToolBench#205]
您好，我已经申请了toolbench api，麻烦通过一下
我的邮箱是qxy118045534@163.com

**Comment by pooruss** [comment]
您好，key已发放请查收

**Comment by xinyiqin** [comment]
您好，使用key进行inference，调用函数的时候报错
"observation": "{\"error\": \"Blocked error...\", \"response\": \"{'message': 'Blocked User. Please contact your API provider.'}\"}"
