### ISSUE TITLE
Generating training data for new tools

### ISSUE THREAD

**Issue by yDing121** [OpenBMB/ToolBench#21]
I would like to generate SFT data for a custom tool, but can't seem to find anything specific related to data generation in the repo. While I can grasp the general paradigm of the data creation process that you followed, there is some confusion about the specifics. Will you release the data generation pipeline or give a more concrete, step-by-step showcase of the SFT data generation? Thanks!

Also, keep up the great work - really looking forward to seeing where this will go.

**Comment by thuqinyj16** [comment]
Hi!  Thanks for your interests in our ToolBench, we've uploaded an early version of data generation codes at [here](https://cloud.tsinghua.edu.cn/f/071fc3e845834191a027/?dl=1). Though the codes are a bit messy, you can refer to them for building a new tool.

And yes! ToolBench will get a very huge update in the next month.

**Comment by yDing121** [comment]
Thank you so much! I will definitely be following the project
