### ISSUE TITLE
Locating Documentation for Currently Used APIs

### ISSUE THREAD

**Issue by CheuWS** [OpenBMB/ToolBench#214]
I am eager to explore the range of APIs available for ToolLLM. As outlined in the paper titled 'TOOLLLM: FACILITATING LARGE LANGUAGE MODELS TO MASTER 16,000+ REAL-WORLD APIS,' the initial collection from RapidAPI includes 53,190 APIs. Following a meticulous filtering process to ensure quality and reliability, ToolLLM results in a final set of 3,451 high-quality tools (16,464 APIs) that are both reliable and functional. Unfortunately, I could not find information on which APIs were filtered out or selected. Could you kindly direct me to the documentation for the currently in-use APIs? I am keen to gain a better understanding of the capabilities offered by ToolLLM.

**Comment by pooruss** [comment]
Hi, the selected apis can be found under `toolenv` in data.zip on [Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J).
