### ISSUE TITLE
基于自定义api训练

### ISSUE THREAD

**Issue by liyoung1992** [OpenBMB/ToolBench#221]
首先非常感谢作者开源ToolBench的源码和训练过程！想咨询一个问题，我们这边有几百个api，一个任务可能会涉及多个api才能解决（这个串联api的过程都是有内部逻辑的），我是否可以单独对我这些内部api做训练（我试了不训练好像不行），从而打造一个内部的api调用智能工具。感谢！

**Comment by pooruss** [comment]
您好，对于使用自己的api，一种无需训练的方式是把您的api处理成我们提供的api信息结构，详见https://github.com/OpenBMB/ToolBench?tab=readme-ov-file#api-customization；若需要训练：
1. 整理api数据，确保api包含必要信息（api doc、参数、调用代码等）
2. 基于api生成instruction，关于instruction生成可以参考此处代码：https://cloud.tsinghua.edu.cn/f/57b7c6cc52fe4426b68c/，关于
3. 调用gpt生成解路径

**Comment by liyoung1992** [comment]
感谢，我使用这个方案尝试下。
