### ISSUE TITLE
训练retriver时api_evaluator.py的第55行，报错too many positional arguments

### ISSUE THREAD

**Issue by Eyict** [OpenBMB/ToolBench#239]
<img width="770" alt="Snipaste_2024-02-23_09-48-07" src="https://github.com/OpenBMB/ToolBench/assets/73412378/b5dcbb42-ff62-4f72-a3d2-29bc995fe553">

**Comment by aidarikako** [comment]
把api_evaluator.py中的
`python
return ndcg_score([true_relevance], [predicted_scores], k)
`
改成下面这个就行
`python
return ndcg_score(y_true = [true_relevance], y_score = [predicted_scores], k = k)
`

**Comment by Eyict** [comment]
感谢

**Comment by Eyict** [comment]
问题已解决
