### ISSUE TITLE
Data generation, Chinese language support and other LLMs

### ISSUE THREAD

**Issue by yDing121** [OpenBMB/ToolBench#25]
I have been able to get the data generation working by patching up the code shared in #21 for tool-augmented SFT data generation and setting up a connection to OpenAI, in specific ```gpt-3.5-turbo```. However, when I tried to adapt the process for a tool in simplified Chinese, I was met with decoding errors as such:
![image](https://github.com/OpenBMB/ToolBench/assets/87789514/da35c2f3-3c8a-48f5-bc0c-5ca952381514)
Since ```gpt-3.5-turbo``` is capable of generation in simplified Chinese, I assumed the issue was somewhere in the code you gave in #21, or somewhere else in the ToolBench environment.

I actually solved the problem while writing up this issue but I'm still going to include it here in case this helps later: you have to set the encoding for the python I/O to an encoding that accommodates for your language e.g. simplified Chinese. No encoding was specified for the ```open()``` that was called to read in the query files, and after specifying the ```utf-8``` encoding everything worked.

Also, I read somewhere on the ToolBench repo that you are working on integration with other LLMs like CPM-Bee. When will this be available, and will there be relevant documentation on how one could use custom-generated SFT data to train these models?

Thanks in advance.

**Comment by thuqinyj16** [comment]
Thanks a lot for repporting the bug in our previous codes!!

For integration with other LLMs and the relevant documentation, we'll make it within this month :)

**Comment by yDing121** [comment]
Sounds good, looking forward to it!
