### ISSUE TITLE
OOM when inference

### ISSUE THREAD

**Issue by Ericmututu** [OpenBMB/ToolBench#26]
Hi ~ 

Thank you for sharing this wonderful work!

I meet the OOM issue when implementing the below script (all default settings) on single 3090 (24G):
```
python toolbench/inference/inference_single_tool.py \
    --tool_name weather \
    --model_path "huggyllama/llama-7b" # just for testing
```

OOM: 
<img width="1795" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/49343975/6ed9146a-7335-45f1-8b50-c9fbcb44f6f4">
This will occur in [`self.model.to(device)`](https://github.com/OpenBMB/BMTools/blob/040d7ce3f19a29ff7401baa2cec7979aae6c5fb9/bmtools/models/llama_model.py#L26)

Note that `requires around 14GB of GPU memory for ToolLLaMA-7B` in README. So, did I do something wrong?

**Comment by thuqinyj16** [comment]
Hi, we've updated the codes, please refer to the new one!
