### ISSUE TITLE
Question about training detail

### ISSUE THREAD

**Issue by zhiyuanc2001** [OpenBMB/ToolBench#260]
Hi, thanks for your good job!  I have some doubts about the training labels.
The `preprocess` function in toolbench/train/train.py just copies the input_ids as the target and then masks the target. However, it seems that there is no position shift operation for target as the LLM should perform next token prediction.
```python
    # Tokenize conversations
    input_ids = tokenizer(
        conversations,
        return_tensors="pt",
        padding="max_length",
        max_length=tokenizer.model_max_length,
        truncation=True,
    ).input_ids
    targets = input_ids.clone()
   ```
Can you help me explain the reasons or there are any details I might have overlooked? Thank you very much.

**Comment by caixd-220529** [comment]
I have the same confuse. Did you solve it?

**Comment by caixd-220529** [comment]
查阅了transformer的[源代码](https://github.com/huggingface/transformers/blob/96eb06286b63c9c93334d507e632c175d6ba8b28/src/transformers/models/llama/modeling_llama.py#L1187)，似乎框架会为我执行shift的操作
