### ISSUE TITLE
Data Overlapping between `single_tool_data/map_7k.json` and `single_tool_test_data/map.json`

### ISSUE THREAD

**Issue by yc1999** [OpenBMB/ToolBench#29]
I find that there exists data overlapping between `single_tool_data/map_7k.json` and `single_tool_test_data/map.json`.

For example:
`single_tool_data/map_7k.json`:
<img width="1069" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/37548571/7678c185-452d-4eaa-bc69-0a24a53766f6">

`single_tool_test_data/map.json`:
<img width="1070" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/37548571/46ad58e5-a9b3-4c0f-8d13-b0de60f210b9">

Can you explain why?  Is that a tag leakage？Thank you！

**Comment by thuqinyj16** [comment]
Hi! Thanks for pointing it out. I believe this is probably a data leakage because we randomly split all the data without checking the overlap in the data. BTW, we will release our toolbench-v2 in 1~2 weeks, there will be a huge update for all the designs.
