### ISSUE TITLE
i can not find tool_llama model,can you provide the link?thank you

### ISSUE THREAD

**Issue by Tomsentable** [OpenBMB/ToolBench#3]

**Comment by pooruss** [comment]
Hi, we have released the lora version [here](https://huggingface.co/pooruss-lsh/tool-llama7b-single-tool-lora). Tool-llama trained with full parameters will be released soon. Please keep following our updates.

**Comment by Tomsentable** [comment]
Thanks for your reply, and the another i want to ask you is "can the weight i fine_tune to replace the "lora_version toolllama weight " as detal weight "

**Comment by pooruss** [comment]
If you train a lora version of tool llama model, sure you can replace the released lora weights with your own  weights. If you train with full parameters, you can replace the /path/to/ToolLLaMA/weights with your saved model path:
`python toolbench/inference/inference_single_tool.py --tool_name weather --model_path /path/to/ToolLLaMA/weights
`

**Comment by Tomsentable** [comment]
thank you! Before infernece(i have  finetuned a  weight),  should i perform this step(apply base weight and delta weight) to get tool_llama weight to inference? And i can not see the delta weight, the link you shared is data not a model.

**Comment by pooruss** [comment]
No, you do not need to apply any delta weight if you fine-tune a model yourself. Just replace the `/path/to/ToolLLaMA/weights` with your own model path~

**Comment by Tomsentable** [comment]
thank you for your reply

**Comment by Tomsentable** [comment]
Dear, the multi data, such as meta_file.json and the first conversation of it, some action look like not a tool use,i want to know what the mean and purpose(i guess that is just to teach LLM how to do, but i don know when inference LLM how to achieve that) 
<img width="683" alt="b97d9f5d81901772eeafe5c572db7e9" src="https://github.com/OpenBMB/ToolBench/assets/135117887/a8ff9678-2b9c-4708-b4c6-57c32f4dea3a">

**Comment by pooruss** [comment]
Detailed information about the tools can be found in BMTools. In multi tools scenario, we select several tools from BMTools.

Specifically, in meta analysis scenario, chemical-prop/meta_analysis/Slides Making/Wikipedia/file_operation/Bing_search are selected. The actions shown above are from Slides Making.

**Comment by Tomsentable** [comment]
Thank you for your reply, and why trained weight has no tokenizer.json  and so on
<img width="182" alt="a7b0a57f36c8ea1b72870d3b39678f3" src="https://github.com/OpenBMB/ToolBench/assets/135117887/9d5644d6-5032-471c-9665-33572dd89341">
<img width="195" alt="d58e7d32623e41c9f228cfc747af3f2" src="https://github.com/OpenBMB/ToolBench/assets/135117887/b347f6d1-51ee-430c-8c63-e9727776c05c">

**Comment by Tomsentable** [comment]
error:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2

**Comment by Tomsentable** [comment]
error occur when training : Failed to clone() tensor with name _fsdp_wrapped_module.model.layers.31.mlp.up_proj.weight on rank 0. This may mean that this state_dict entry could point to invalid memory regions after returning from state_dict() call if this parameter is managed by FSDP,
