### ISSUE TITLE
工具注册一定要使用openai吗

### ISSUE THREAD

**Issue by whrljt** [OpenBMB/ToolBench#30]
python BMTools/host_local_tools.py

请问Llama模型评测时使用本地模型前是否一定要进行python BMTools/host_local_tools.py的工具注册；工具注册只能使用openai的embding吗？

**Comment by rliu09** [comment]
可以填上假的，亲测有效

**Comment by thuqinyj16** [comment]
工具注册不需要绑定openai的embedding，另外我们已经更新新的ToolBench代码，支持16000+ API，敬请使用～

**Comment by whrljt** [comment]
> 工具注册不需要绑定openai的embedding，另外我们已经更新新的ToolBench代码，支持16000+ API，敬请使用～
多谢回复！再问下新版本的ToolBench还可以像BMTools里一样进行自定义工具注册吗？

**Comment by thuqinyj16** [comment]
可以的，新版本的ToolBench原则上支持所有形式的API，只要API的文档写得足够好就可以
