### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by WeiminXiong** [OpenBMB/ToolBench#309]
Hi, I've submitted the form. Could you check it and send me the API key to access the RapidAPI server? My email is [wmxiong@pku.edu.cn](mailto:wmxiong@pku.edu.cn). Thanks a lot!

**Comment by sailaoda** [comment]
Hello, thank you for your attention, we have sent the relevant key according to the email address on your issue. At the same time we also updated the application form of the key address, now is https://forms.gle/S4hqVLtnqeXcNTCJA, I'm sorry before scrap lead to form link information didn't reply in time.
