### ISSUE TITLE
Request for API Key

### ISSUE THREAD

**Issue by CDMY0417** [OpenBMB/ToolBench#313]
Hi, I really appreciate your work and looking forward for the inference.
I have requested the API key about a month ago, but I haven't gotten a response.
Hope you could send me the key for the RapidAPI server.
My email is [tikiliki0417@snu.ac.kr](mailto:tikiliki0417@snu.ac.kr).

Thanks for your appreciation.

**Comment by sailaoda** [comment]
Hello, thank you for your attention, we have sent the relevant key according to the email address on your issue. At the same time we also updated the application form of the key address, now is https://forms.gle/S4hqVLtnqeXcNTCJA, I'm sorry before scrap lead to form link information didn't reply in time.
