### ISSUE TITLE
Is the server still working properly?

### ISSUE THREAD

**Issue by Octobrist** [OpenBMB/ToolBench#324]
I use **http://8.130.32.149:8080/rapidapi** and **http://39.105.143.28:8080/rapidapi** as the toolbench_url. However, all API calls return 500 - Internal Server Error. Strangely, the server was accessible before. 

Has my IP address been added to the blacklist due to the frequent calling?

**Comment by suyan-liang** [comment]
I have the same question

**Comment by suyan-liang** [comment]
> I use **http://8.130.32.149:8080/rapidapi** and **http://39.105.143.28:8080/rapidapi** as the toolbench_url. However, all API calls return 500 - Internal Server Error. Strangely, the server was accessible before.
> 
> Has my IP address been added to the blacklist due to the frequent calling?

https://github.com/THUNLP-MT/StableToolBench/issues/18
I changed my toolbenurl to http://39.105.143.28:8080/rapidapi and it works.

**Comment by Octobrist** [comment]
> > I use **http://8.130.32.149:8080/rapidapi** and **http://39.105.143.28:8080/rapidapi** as the toolbench_url. However, all API calls return 500 - Internal Server Error. Strangely, the server was accessible before.
> > Has my IP address been added to the blacklist due to the frequent calling?
> 
> [THUNLP-MT/StableToolBench#18](https://github.com/THUNLP-MT/StableToolBench/issues/18) I changed my toolbenurl to http://39.105.143.28:8080/rapidapi and it works.

Stiil no work for me ~~~~~~~~~

**Comment by Octobrist** [comment]
working proprly now~, thank team!
