### ISSUE TITLE
OOM during LoRA training using data/toolllama_G123_dfs_train.json

### ISSUE THREAD

**Issue by codewangg** [OpenBMB/ToolBench#33]
Hi, I'm trying to reproduce the result by Training a LoRA version using the training data provided: data/toolllama_G123_dfs_train.json, 
It's so bizarre that the machine got quickly OOMed (CPU memory OOM, instead of GPU memory), any idea on what might go wrong? 
Why there's so much memory being used?
```
export PYTHONPATH=./
deepspeed --master_port=20001 toolbench/train/train_long_seq_lora.py \
    --model_name_or_path /home/gzc/data/llama/7B_new  \
    --data_path  data/toolllama_G123_dfs_train.json \
    --eval_data_path  data/toolllama_G123_dfs_eval.json \
    --conv_template tool-llama-single-round \
    --bf16 True \
    --output_dir toolllama_lora \
    --num_train_epochs 5 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "epoch" \
    --prediction_loss_only \
    --save_strategy "epoch" \
    --save_total_limit 8 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.04 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --model_max_length 8192 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --deepspeed ds_configs/stage2.json \
    --report_to tensorboard
```

<img width="1197" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/19606731/480b9bd4-6144-425f-ba88-a2eedfa9e75d">

**Comment by thuqinyj16** [comment]
Hi~ Thanks for your interests. We're using a much longer sequence length (8192) than the vanilla LLaMA, and the memory would be thus larger. 

However, LoRA can be trained using 2 40G A100 GPUs (we've tested it), the codes are optimized for GPU not for CPU, we'll check details later why CPU costs so much memory.

**Comment by codewangg** [comment]
Yea, thanks for the quick response, I'm using 8 3090 GPUs so it shouldn't be a problem with GPUs, It's just surprising that it cost more than 200 GB of CPU memory, the short sequence train.py gives me the same CPU OOM too.

**Comment by codewangg** [comment]
Yes with the device map added, GPUs are utilized when loading the pre-trained model, thanks for the update!
I got another blocker though, as you mentioned this training process has been tested on 2 40G A100 GPUs, but I received OOM on GPU where I got 8* 24GB GTX 3090 on my host machine, this doesn't look right to me.
To mitigate this, I've been reducing the batch size to 1 and using ds_configs/stage3.json (with CPU offload).
Is there any other method I can use to reduce the GPU memory usage?

Training params I've been using:
```
export PYTHONPATH=./
deepspeed --master_port=20001 toolbench/train/train_long_seq_lora.py \
    --model_name_or_path /home/gzc/data/llama/7B_new  \
    --data_path  data/toolllama_G123_dfs_train.json \
    --eval_data_path  data/toolllama_G123_dfs_eval.json \
    --conv_template tool-llama-single-round \
    --bf16 True \
    --output_dir /home/gzc/disk5/ShorteningToolChains/ToolBench2/output/ \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "epoch" \
    --prediction_loss_only \
    --save_strategy "epoch" \
    --save_total_limit 8 \
    --learning_rate 5e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.04 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --model_max_length 8192 \
    --gradient_checkpointing True \
    --lazy_preprocess True \
    --deepspeed ds_configs/stage3.json \
    --report_to tensorboard \
    --gradient_checkpointing True 
```

**Comment by zhaojunGUO** [comment]
> To mitigate this, I've been reducing the batch size to 1 and using ds_configs/stage3.json (with CPU offload).

same issue
