### ISSUE TITLE
评测数据对应的rapid API 是需要先手动订阅才可以评测吗？

### ISSUE THREAD

**Issue by zweny** [OpenBMB/ToolBench#34]
尝试推理评测过程中，调用过程会遇到许多api error，例如没有订阅、超过限制、504 error。请问这些都会影响到模型的评估结果吗？

**Comment by thuqinyj16** [comment]
会影响。我们有一套自动订阅的脚本，会先把所有考虑的API都订阅一遍，这样就不会遇到没有订阅的问题了。我们通过这种方式订阅了多个账号，一定程度上解决了超过限制的问题。504 error这种如果是rapidAPI内部的问题是没法解决的。

我们考虑这几天把自动订阅的脚本放出来🤔️
