### ISSUE TITLE
提升代码可读性

### ISSUE THREAD

**Issue by wangyuxinwhy** [OpenBMB/ToolBench#38]
首先很感谢您能开源此项目和论文，但是在阅读源码的过程中，实在太痛苦了。有以下几个建议

1. 变量命名，命名应该尽量符合社区规范，这样可以让读者更好的理解变量的作用，可以参考 PEP8
2. 基础语法，适当学习一下 python 的基础语法，比如，如何做单行注释等
3. 函数抽象，[DFS 函数](https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Algorithms/DFS.py#L114C75-L114C75) 超过 230 多行，可以做适当的抽象
4. 代码格式，可以使用 black 等工具做代码格式化

实在抱歉，看了源码真的忍不住.... 再次感谢您的开源

**Comment by thuqinyj16** [comment]
您好，感谢对我们工作的认可。由于时间人力有限，参与代码构建的多位同学尚未统一代码风格，我们将在未来两周内规范代码，如果您感兴趣的话也可以提PR共建～
