### ISSUE TITLE
模型咨询

### ISSUE THREAD

**Issue by michaelxu1107** [OpenBMB/ToolBench#44]
您好：

        很棒的项目
        
        问一下后续有没有计划发布基于其他开源大模型微调训练的工具模型？
        我之前有使用过开源的BMTools，将openai换成了chatglm，但效果很不理想，不知道基于toolllm效果会不会有所提升
        
        谢谢

**Comment by thuqinyj16** [comment]
你好，感谢对我们工作的关注，我们已经开源了用LLaMA-1微调的代码和模型，这一周会支持LLaMA-2。后续会继续支持例如CPM-bee等中文领域领先的大模型，欢迎关注与共建👏
