### ISSUE TITLE
在Training Retriever 时Data preprocessing 错误

### ISSUE THREAD

**Issue by double-fire-0** [OpenBMB/ToolBench#48]
按照readme执行
export PYTHONPATH=./
python data/preprocess_retriever_data.py \
    --query_file data/instruction/G1_query.json \
    --index_file data/test_query_ids/G1_instruction_test_query_ids.json \
    --dataset_name G1 \
    --output_dir data/retrieval/G1

preprocess_retriever_data.py 不在data文件夹中，而是在preprocess文件夹中

执行preprocess文件夹中的对应文件时报错：
Traceback (most recent call last):
  File "/Users/xxx/Desktop/xxx/ToolBench/preprocess/preprocess_retriever_data.py", line 84, in <module>
    process_data(query_train, train_pairs)
  File "/Users/xxx/Desktop/xxx/ToolBench/preprocess/preprocess_retriever_data.py", line 81, in process_data
    query_id = query_id_map.setdefault(query, len(query_id_map) + 1)
TypeError: unhashable type: 'list'

**Comment by pooruss** [comment]
您好，感谢指正，我们已经根据问题更新了readme以及新的处理脚本～

**Comment by double-fire-0** [comment]
谢谢，现在没问题了
