### ISSUE TITLE
too slowly

### ISSUE THREAD

**Issue by Tomsentable** [OpenBMB/ToolBench#5]
I inference the singletools, but it inference too slow(4A100,40G)

**Comment by pooruss** [comment]
Hi, can you provide more information, such as how slow, or maybe the inference pipeline is stuck in somewhere else instead of the model inference stage.

**Comment by Tomsentable** [comment]
<img width="626" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/135117887/a39cb6e9-0171-46ab-9d53-0c6294449a96">
,i kill some tools which need openaikey(that means i have no openaikey used), only keep weather api and working on 127.0.0.1:7860,then loading the weight(which is loaded normal,not slow),and inference is slowly

**Comment by Tomsentable** [comment]
thanks, where inference pipeline code?

**Comment by Tomsentable** [comment]
<img width="845" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/135117887/a6f41ed7-7ae1-46c5-988e-0294f813366b">
when the code inference here,it becomes slowly

**Comment by Tomsentable** [comment]
<img width="862" alt="image" src="https://github.com/OpenBMB/ToolBench/assets/135117887/0e4a331e-d818-4f46-9b55-f0b332a3eb62">
i find the slowly code,but i do not know why
