### ISSUE TITLE
ToolLLaMA是基于LLaMA基座模型还是Vicuna(or Alpaca)模型finetune得到的？

### ISSUE THREAD

**Issue by HIT-cwh** [OpenBMB/ToolBench#51]
您好！很感激您开源的工作，这里有个问题想请教下。

看到您论文3.3章中提到了LLaMA基座模型不好直接拿来finetune工具使用能力，因此使用Vicuna 或者 Alpaca模型来进行finetune。
`Since the original LLaMA checkpoint is not fine-tuned toward any downstream task, it cannot be leveraged to use tools directly. Instead, we choose two LLaMA variants that have been fine-tuned for general-purpose instruction tuning on dialogue data, i.e., Vicuna (Chiang et al., 2023) and Alpaca (Taori et al., 2023).`

[readme中 train lora version的命令](https://github.com/OpenBMB/ToolBench/blob/master/README.md?plain=1#L216)好像只用了LLaMA的基座模型finetune。想请教下基于哪个模型进行finetune效果会比较好呢？衷心感谢！

**Comment by pooruss** [comment]
您好～ToolLLaMA是基于LLaMA微调的，您引用到的论文内容是在阐述基线模型的选择；对于基座模型的说明是在3.3中的第一段。我们会考虑将Vicuna或Alpaca作为基座模型与LLaMA作为基座模型进行比较～
