### ISSUE TITLE
请问使用LORA微调的最低硬件配置是多少

### ISSUE THREAD

**Issue by meareabc** [OpenBMB/ToolBench#52]
我现在使用四卡3090仍然OOM，请问是因为3090单卡显存的限制还是总体显存的限制

**Comment by pooruss** [comment]
请问您的per_device_train_batch_size是多少呢，per_device_train_batch_size设为1会占大概20G/卡，设为4会占大概37G/卡

**Comment by meareabc** [comment]
> 请问您的per_device_train_batch_size是多少呢，per_device_train_batch_size设为1会占大概20G/卡，设为4会占大概37G/卡

您好，不是在训练阶段出的错误，而是在读取预训练模型出的错。因为网络原因，我先使用的是之前下载的其他llama预训练模型。参数如下
"version": "0.2.0",
    "configurations": [
        {
            "name": "Python: 当前文件",
            "type": "python",
            "request": "launch",
            "program": "/home/fanzhengjie/.conda/envs/deepspeed/bin/deepspeed",
            "console": "integratedTerminal",
            "cwd": "${fileDirname}",
            "args": [
                "--master_port=20001",
                "toolbench/train/train_long_seq_lora.py",
                "--model_name_or_path=/home/fanzhengjie/kopl_code/huggingface/llama-7b-hf",
                "--data_path=data/toolllama_G123_dfs_train.json",
                "--eval_data_path=data/toolllama_G123_dfs_eval.json",
                "--conv_template=tool-llama-single-round",
                "--bf16=True",
                "--output_dir=toolllama_lora",
                "--num_train_epochs=5",
                "--per_device_train_batch_size=1",
                "--per_device_eval_batch_size=1",
                "--gradient_accumulation_steps=2",
                "--evaluation_strategy=epoch",
                "--prediction_loss_only=true",
                "--save_strategy=epoch",
                "--save_total_limit=8",
                "--learning_rate=5e-5",
                "--weight_decay=0.",
                "--warmup_ratio=0.04",
                "--lr_scheduler_type=cosine",
                "--logging_steps=1",
                "--model_max_length=8192",
                "--gradient_checkpointing=True",
                "--lazy_preprocess=True", 
                "--deepspeed=ds_configs/stage2.json",
                "--report_to=none",   
            ],
            "env": {"CUDA_VISIBLE_DEVICES":"2,3,4,5,6,7"},
            //"justMyCode": true
        }
    ]

**Comment by meareabc** [comment]
报错信息如下
```
发生异常: OutOfMemoryError
CUDA out of memory. Tried to allocate 172.00 MiB (GPU 5; 23.70 GiB total capacity; 22.87 GiB already allocated; 78.88 MiB free; 22.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  File "/home/fanzhengjie/kopl_code/toolGPT/ToolBench-master/toolbench/train/train_long_seq_lora.py", line 111, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/fanzhengjie/kopl_code/toolGPT/ToolBench-master/toolbench/train/train_long_seq_lora.py", line 169, in <module>
    train()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 5; 23.70 GiB total capacity; 22.87 GiB already allocated; 78.88 MiB free; 22.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by meareabc** [comment]
我在取消deepspeed后，模型成功的加载在了多个GPU上，但是报了个warning。我不知道是不是因为没有使用deepspeed的问题。另外，requirements中的**torch>=1.12.0**似乎需要更正为**torch>=2.0.0**。因为[该条语句](https://github.com/OpenBMB/ToolBench/blob/master/toolbench/train/llama_flash_attn_monkey_patch.py#L48)的函数似乎[并没有](https://github.com/oobabooga/text-generation-webui/issues/2260)在1.13.1实现。
以下分别是我目前的参数和warning。
`"version": "0.2.0",
    "configurations": [
        {
            "name": "Python: 当前文件",
            "type": "python",
            "request": "launch",
            "program": "${file}",//"program": "/home/fanzhengjie/.conda/envs/deepspeed/bin/deepspeed",
            "console": "integratedTerminal",
            "cwd": "/home/fanzhengjie/kopl_code/toolGPT/ToolBench-master/",
            "args": [
                // "--master_port=20001",
                // "toolbench/train/train_long_seq_lora.py",
                "--model_name_or_path=/home/fanzhengjie/kopl_code/tloen/yahma-7b-hf",
                "--data_path=data/toolllama_G123_dfs_train.json",
                "--eval_data_path=data/toolllama_G123_dfs_eval.json",
                "--conv_template=tool-llama-single-round",
                "--bf16=True",
                "--output_dir=toolllama_lora",
                "--num_train_epochs=5",
                "--per_device_train_batch_size=1",
                "--per_device_eval_batch_size=1",
                "--gradient_accumulation_steps=2",
                "--evaluation_strategy=epoch",
                "--prediction_loss_only=true",
                "--save_strategy=epoch",
                "--save_total_limit=8",
                "--learning_rate=5e-5",
                "--weight_decay=0.",
                "--warmup_ratio=0.04",
                "--lr_scheduler_type=cosine",
                "--logging_steps=1",
                "--model_max_length=8192",
                "--gradient_checkpointing=True",
                "--lazy_preprocess=True", 
                //"--deepspeed=ds_configs/stage2.json",
                "--report_to=none",   
            ],
            //"env": {"CUDA_VISIBLE_DEVICES":"0,1,2,3,4,5,6,7"},
            //"justMyCode": true
        }
    ]`

`WARNING:root:gradient checkpointing with lora makes requires_grad incorrect and needs a monkey patch in Trainer or the wrapped model's forward. ref: https://github.com/lm-sys/FastChat/pull/138#issuecomment-1509172198`

**Comment by meareabc** [comment]
最新的进展，目前可以在deepspeed_stage_3和上面说的取消deepspeed两种情况下运行，两者似乎都是将模型切片后存在了多个gpu上。而如果我参数使用stage2的话，模型会就爆显存。

**Comment by pooruss** [comment]
当前lora模型加载需要26G的显存，在我们之前的代码测试中[tloen](https://github.com/tloen/alpaca-lora)的效率相对较低，所以我们选择了参考[FastChat](https://github.com/lm-sys/FastChat)

**Comment by meareabc** [comment]
> 当前lora模型加载需要26G的显存，在我们之前的代码测试中[tloen](https://github.com/tloen/alpaca-lora)的效率相对较低，所以我们选择了参考[FastChat](https://github.com/lm-sys/FastChat)

好的，谢谢了。另外请问一个小问题，如果不采用deepspeed而是直接运行的话，是否需要额外写优化器和batch，如[tloen](https://github.com/tloen/alpaca-lora/blob/main/finetune.py#L236)

**Comment by meareabc** [comment]
目前八卡训练似乎跑不起来，都会报OOM。。
如果用stage3的deepspeed的话，会在第一次执行`attn_output= F.scaled_dot_product_attention(query_states,key_states,value_states,dropout_p=0.0, is_causal=True)`时报OOM

如果不适用deepspeed的话，会在执行中间报OOM，显存使用情况如下

```
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A    368635      C   ...envs/deepspeed/bin/python     6167MiB |
|    0   N/A  N/A   3106971      C   ...vs/data_center/bin/python     2039MiB |
|    1   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A    368635      C   ...envs/deepspeed/bin/python     6777MiB |
|    2   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A    368635      C   ...envs/deepspeed/bin/python     6777MiB |
|    3   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A    368635      C   ...envs/deepspeed/bin/python     6777MiB |
|    4   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    4   N/A  N/A    368635      C   ...envs/deepspeed/bin/python     6777MiB |
|    5   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    5   N/A  N/A    368635      C   ...envs/deepspeed/bin/python    22951MiB |
|    6   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    6   N/A  N/A    368635      C   ...envs/deepspeed/bin/python    23131MiB |
|    7   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    7   N/A  N/A    368635      C   ...envs/deepspeed/bin/python      653MiB |
+-----------------------------------------------------------------------------+

```

**Comment by meareabc** [comment]
以下为max_token=4096，batch=1时的显存使用情况
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A    371096      C   ...envs/deepspeed/bin/python     9129MiB |
|    0   N/A  N/A   3106971      C   ...vs/data_center/bin/python     2039MiB |
|    1   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A    371096      C   ...envs/deepspeed/bin/python    10205MiB |
|    2   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A    371096      C   ...envs/deepspeed/bin/python    10205MiB |
|    3   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A    371096      C   ...envs/deepspeed/bin/python    10205MiB |
|    4   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    4   N/A  N/A    371096      C   ...envs/deepspeed/bin/python    10205MiB |
|    5   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    5   N/A  N/A    371096      C   ...envs/deepspeed/bin/python    10205MiB |
|    6   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    6   N/A  N/A    371096      C   ...envs/deepspeed/bin/python    11425MiB |
|    7   N/A  N/A     14964      G   /usr/lib/xorg/Xorg                  4MiB |
|    7   N/A  N/A    371096      C   ...envs/deepspeed/bin/python      653MiB |
+-----------------------------------------------------------------------------+
```

**Comment by pooruss** [comment]
好的，感谢您的贡献～

如有进一步相关的问题我们可以继续讨论，如果暂时没有或者有其他方面的问题我们可以新开一个issue讨论哈～

**Comment by gewenbin0992** [comment]
> 我在取消deepspeed后，模型成功的加载在了多个GPU上，但是报了个warning。我不知道是不是因为没有使用deepspeed的问题。另外，requirements中的**torch>=1.12.0**似乎需要更正为**torch>=2.0.0**。因为[该条语句](https://github.com/OpenBMB/ToolBench/blob/master/toolbench/train/llama_flash_attn_monkey_patch.py#L48)的函数似乎[并没有](https://github.com/oobabooga/text-generation-webui/issues/2260)在1.13.1实现。 以下分别是我目前的参数和warning。
> 
> ```
> "version": "0.2.0",
>     "configurations": [
>         {
>             "name": "Python: 当前文件",
>             "type": "python",
>             "request": "launch",
>             "program": "${file}",//"program": "/home/fanzhengjie/.conda/envs/deepspeed/bin/deepspeed",
>             "console": "integratedTerminal",
>             "cwd": "/home/fanzhengjie/kopl_code/toolGPT/ToolBench-master/",
>             "args": [
>                 // "--master_port=20001",
>                 // "toolbench/train/train_long_seq_lora.py",
>                 "--model_name_or_path=/home/fanzhengjie/kopl_code/tloen/yahma-7b-hf",
>                 "--data_path=data/toolllama_G123_dfs_train.json",
>                 "--eval_data_path=data/toolllama_G123_dfs_eval.json",
>                 "--conv_template=tool-llama-single-round",
>                 "--bf16=True",
>                 "--output_dir=toolllama_lora",
>                 "--num_train_epochs=5",
>                 "--per_device_train_batch_size=1",
>                 "--per_device_eval_batch_size=1",
>                 "--gradient_accumulation_steps=2",
>                 "--evaluation_strategy=epoch",
>                 "--prediction_loss_only=true",
>                 "--save_strategy=epoch",
>                 "--save_total_limit=8",
>                 "--learning_rate=5e-5",
>                 "--weight_decay=0.",
>                 "--warmup_ratio=0.04",
>                 "--lr_scheduler_type=cosine",
>                 "--logging_steps=1",
>                 "--model_max_length=8192",
>                 "--gradient_checkpointing=True",
>                 "--lazy_preprocess=True", 
>                 //"--deepspeed=ds_configs/stage2.json",
>                 "--report_to=none",   
>             ],
>             //"env": {"CUDA_VISIBLE_DEVICES":"0,1,2,3,4,5,6,7"},
>             //"justMyCode": true
>         }
>     ]
> ```
> 
> ```
> WARNING:root:gradient checkpointing with lora makes requires_grad incorrect and needs a monkey patch in Trainer or the wrapped model's forward. ref: https://github.com/lm-sys/FastChat/pull/138#issuecomment-1509172198
> ```

这条代码确实需要torch 2.0，但是 transformers 要用 torch._six，这在torch 2.0中会报不存在，怎么解的？
