### ISSUE TITLE
weather_v14 这个 api 调用不成功

### ISSUE THREAD

**Issue by xiaobaibai1** [OpenBMB/ToolBench#53]
不论使用自己的 rapidapi_key 还是 toolbench_key。拿到的返回都是：
Observation: {"error": "", "response": "{'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/ke
ys for more info.'}"}

**Comment by pooruss** [comment]
您好～
由于工具的实时性，我们无法保证某个api能一直被成功地调用；目前的免费工具集也存在一部分api完全失效或不正常，我们将这部分api包括在内，以检验模型handle调用返回出错时的能力。未来我们计划扩充付费的工具，进一步提升工具的整体质量

**Comment by xiaobaibai1** [comment]
可以，我现在问，what't the weather like today? 直接就定位到  weather_14。那您知道哪个 weather 相关的工具是可用的吗？

**Comment by pooruss** [comment]
可以用我们的api检索器去检索weather相关的工具然后看哪些是可用的哈
