### ISSUE TITLE
如何进行测试

### ISSUE THREAD

**Issue by trestad** [OpenBMB/ToolBench#54]
作者们好：

在本repo给出的命令中，inference使用的数据都是一个demo json，请问如何进行对test set进行infer？

我看到在test_query_ids目录下的文件似乎指明了G1，G2，G3的测试数据id，所以为了infer测试集（以G1为例），我要做的事情是在读取完data/instruction/G1_query.json之后，按照test_query_ids/G1_category_test_query_ids.json的id进行筛选？每个等级的测试都是只有100条测试集对吗。

如有误解麻烦指正，十分感谢

**Comment by trestad** [comment]
另外，还行请教一下作者们DFS.py文件中的self.callbacks的作用是什么，我在infer的时候检查callbacks的值，发现始终是空list:[].

**Comment by pooruss** [comment]
> 

您好～是的，test_query_ids下就是测试集中所有query对应的query id，可以在data/instruction下的数据中提取对应query
