### ISSUE TITLE
关于数据集如何构造问答对

### ISSUE THREAD

**Issue by x2ss** [OpenBMB/ToolBench#55]
您好，

感谢您开源了如此优秀的工作并给出了训练数据集。

我看了数据集后，不太能理解，主要不是我知道的那种问答对的形式（比如这样的{"prompt": "问题：你从哪里来\n", "completion": ["南方"}），因为我理解不是问答对的形式似乎不能微调，不知道您给出的data_example中例如
[10_ChatGPT_DFS_woFilter_w2.json](https://github.com/OpenBMB/ToolBench/blob/master/data_example/answer/G1_answer/10_ChatGPT_DFS_woFilter_w2.json)
哪一部分是问，哪一部分是答？或者您是怎么从这个json构造问答对的？

麻烦您了，期盼您的回复！
祝好！

**Comment by pooruss** [comment]
您好，您可以参考readme里的数据预处理部分的说明，将给出的data_example处理成问答的形式，具体脚本如下：
```bash
export PYTHONPATH=./
python preprocess/preprocess_toolllama_data.py \
    --tool_data_dir data_example/answer/G1_answer \
    --method DFS_woFilter_w2 \
    --output_file toolllama_G1_dfs.json
```

然后查看toolllama_G1_dfs.json数据内容

**Comment by x2ss** [comment]
> 您好，您可以参考readme里的数据预处理部分的说明，将给出的data_example处理成问答的形式，具体脚本如下：
> 
> ```shell
> export PYTHONPATH=./
> python preprocess/preprocess_toolllama_data.py \
>     --tool_data_dir data_example/answer/G1_answer \
>     --method DFS_woFilter_w2 \
>     --output_file toolllama_G1_dfs.json
> ```
> 
> 然后查看toolllama_G1_dfs.json数据内容

感谢！我去操作一下试试，再次感谢您的回复。
