### ISSUE TITLE
支持自己的API调用？

### ISSUE THREAD

**Issue by lunalulu** [OpenBMB/ToolBench#56]
感谢您的工作
请问，如果我想把这个工作应用到私有的API接口，比如让模型帮我执行预定会议室这样的操作，是不是可行的呢？
如果可行，是需要制作单独的指令数据集，并训练后使用吗？

非常感谢您的答复！

**Comment by thuqinyj16** [comment]
是可行的。我们模型已经验证了非常强的泛化能力，只要把新的API格式定义好（写成类似我们支持的16000+API的API doc形式即可），就可以直接使用。

**Comment by lunalulu** [comment]
感谢🙏

---- 回复的原邮件 ----
| 发件人 | Yujia ***@***.***> |
| 发送日期 | 2023年08月15日 08:29 |
| 收件人 | OpenBMB/ToolBench ***@***.***> |
| 抄送人 | lunalulu ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [OpenBMB/ToolBench] 支持自己的API调用？ (Issue #56) |

是可行的。我们模型已经验证了非常强的泛化能力，只要把新的API格式定义好（写成类似我们支持的16000+API的API doc形式即可），就可以直接使用。

**Comment by lyn233** [comment]
您好 ， 您说的API doc形式是否就是instrction下的G1_query.json格式的文件？

**Comment by mMrBun** [comment]
能否在readme中给出最小例子？

**Comment by huhy-uniplore** [comment]
您好，您说的  "写成类似我们支持的16000+API的API doc形式即可"  ，这个API doc在哪呢？

**Comment by pooruss** [comment]
> 您好，您说的 "写成类似我们支持的16000+API的API doc形式即可" ，这个API doc在哪呢？

API doc在[Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)的data/toolenv/tools目录，每个工具会有对应的doc json文件

**Comment by mMrBun** [comment]
我自己做了一个demo，去掉了RapidAPI，需要修改的文件有
- data/retrieval/G1/corpus.tsv 按照上面的格式把自己的API加进去，这里要注意缩进，docid和document_content之间用制表符分隔的，不然会报json decode的异常
- data/toolenv/tools/ 在这里创建一个新的分类，按照其他分类下的格式写调用脚本(api.py)，还有[上面](https://github.com/OpenBMB/ToolBench/issues/56#issuecomment-1683351496)作者回复的json文件，这里的api会被加载到task_list里。
大致目录如下
![image](https://github.com/OpenBMB/ToolBench/assets/52190211/be39b405-0eda-4cb0-9cc1-ab16369398bd)

**Comment by pooruss** [comment]
> 能否在readme中给出最小例子？

您好，API定制的相关说明和例子已经更新到README～

**Comment by pooruss** [comment]
> 我自己做了一个demo，去掉了RapidAPI，需要修改的文件有
> 
> * data/retrieval/G1/corpus.tsv 按照上面的格式把自己的API加进去，这里要注意缩进，docid和document_content之间用制表符分隔的，不然会报json decode的异常
> * data/toolenv/tools/ 在这里创建一个新的分类，按照其他分类下的格式写调用脚本(api.py)，还有[上面](https://github.com/OpenBMB/ToolBench/issues/56#issuecomment-1683351496)作者回复的json文件，这里的api会被加载到task_list里。
>   大致目录如下
>   ![image](https://user-images.githubusercontent.com/52190211/261509056-be39b405-0eda-4cb0-9cc1-ab16369398bd.png)

非常感谢您的贡献！

**Comment by lunalulu** [comment]
@mMrBun @pooruss  非常感谢两位，你们太棒了~我也去试试

**Comment by huhy-uniplore** [comment]
> > 您好，您说的 "写成类似我们支持的16000+API的API doc形式即可" ，这个API doc在哪呢？
> 
> API doc在[Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)的data/toolenv/tools目录，每个工具会有对应的doc json文件

>
>



> > 您好，您说的 "写成类似我们支持的16000+API的API doc形式即可" ，这个API doc在哪呢？
> 
> API doc在[Google Drive](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)的data/toolenv/tools目录，每个工具会有对应的doc json文件

感谢您的回复，我知道啦
