### ISSUE TITLE
关于数据集生成的问题

### ISSUE THREAD

**Issue by YishuiLi** [OpenBMB/ToolBench#59]
在训练ToolLLaMA时使用的训练集为toolllama_G123_dfs_train.json，该json文件由data/answer目录下的一系列json通过preprocess/preprocess_toolllama_data.py脚本处理后生成。
想请问下data/answer目录下的一系列json（如：[10_ChatGPT_DFS_woFilter_w2.json](https://github.com/OpenBMB/ToolBench/blob/master/data_example/answer/G1_answer/10_ChatGPT_DFS_woFilter_w2.json)）是否是通过ChatGPT生成的，生成的步骤能否说明一下。

期盼您的回复！
祝好！

**Comment by pooruss** [comment]
您好～
answer下的json是由ChatGPT生成的，可以直接运行chagtpt做inference的脚本生成，如下：
```bash
export TOOLBENCH_KEY=""
export OPENAI_KEY=""
export PYTHONPATH=./
python toolbench/inference/qa_pipeline.py \
    --tool_root_dir data/toolenv/tools/ \
    --backbone_model chatgpt_function \
    --openai_key $OPENAI_KEY \
    --max_observation_length 1024 \
    --method DFS_woFilter_w2 \
    --input_query_file data/instruction/inference_query_demo.json \
    --output_answer_file data/answer/chatgpt_dfs \
    --toolbench_key $TOOLBENCH_KEY
```

**Comment by YishuiLi** [comment]
> 您好～ answer下的json是由ChatGPT生成的，可以直接运行chagtpt做inference的脚本生成，如下：
> 
> ```shell
> export TOOLBENCH_KEY=""
> export OPENAI_KEY=""
> export PYTHONPATH=./
> python toolbench/inference/qa_pipeline.py \
>     --tool_root_dir data/toolenv/tools/ \
>     --backbone_model chatgpt_function \
>     --openai_key $OPENAI_KEY \
>     --max_observation_length 1024 \
>     --method DFS_woFilter_w2 \
>     --input_query_file data/instruction/inference_query_demo.json \
>     --output_answer_file data/answer/chatgpt_dfs \
>     --toolbench_key $TOOLBENCH_KEY
> ```

感谢您的回复！谢谢！
