### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by HMJW** [OpenBMB/ToolBench#60]
启动toolbench_server.py后，就占用了大约28G显存，推理的时候马上就OOM了。请问这个正常吗？

**Comment by pooruss** [comment]
您好～推理时随着工具调用链变长，模型输入的sequence length会变长，最后可能会导致OOM，在我们的实验中40G显存绝大多数情况下都不会出现OOM

**Comment by xiaobaibai1** [comment]
我测试，OOM 真的特别容易出现。我打印了OOM时，模型处理的token数，有的时候 2000多，有的时候 1000 出头。 

RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 47.54 GiB total capacity; 44.72 GiB already allocated; 11.75 MiB free; 46.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by pooruss** [comment]
可以提供一下您测试的case吗，我们这边测试的时候2000左右token时占用32G左右的显存

**Comment by jackhexiangyu12** [comment]
我运行toolbench_server.py的时候，只用了单张gpu0的3090，显存超过24G就报错OOM了，请问可以放在8张3090上一起运行吗？
