### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by chenjw505** [OpenBMB/ToolBench#62]
训练数据里面，看到有一些 模型选错function，并且到最后answer也不正确， 这种数据为什么也要给模型训练使用呢？ 这种一条路走到黑的数据，是不是剔除比较好？

**Comment by thuqinyj16** [comment]
这是一个开放的问题，比如某些instruction如果就是没法用当前的API解决，那其实模型在多次尝试后决定退出，这反而应该是一个“正确”的，而并不是让模型强行说“我做完了”

虽然这些数据可能不是“成功完成”了的数据，但是让模型学会这个过程中学会API调用错误了的话下一步应该怎么办

欢迎大家在这个issue下继续讨论！

**Comment by x2ss** [comment]
和cv正负样本一个道理吧。。。
