### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by xiaobaibai1** [OpenBMB/ToolBench#63]
我打印了OOM时，模型处理的token数，有的时候 2000多，有的时候 1000 出头。

RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 47.54 GiB total capacity; 44.72 GiB already allocated; 11.75 MiB free; 46.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by chenglong0313** [comment]
我在40g的卡上部署的后端，post的时候也总是报oom，是tokens太长了很消耗显存吗，还是我的环境有问题？

**Comment by chenglong0313** [comment]
确实挺占显存的，7B模型，我只是测试一下What is the weather in New York today，显存最多占用超过了60G

**Comment by pooruss** [comment]
您好，大家可以在这个issue下讨论～https://github.com/OpenBMB/ToolBench/issues/60
