### ISSUE TITLE
Could you give me the ToolBench key quickly?

### ISSUE THREAD

**Issue by yamengxi** [OpenBMB/ToolBench#65]
I filled out the [form](https://forms.gle/oCHHc8DQzhGfiT9r6) for the ToolBench key last Friday (2023-08-11).
But I haven't received the key up to now (2023-08-14).
Could please you give me the ToolBench key quickly?
Thanks!

**Comment by thuqinyj16** [comment]
We'll provide it today. Thanks for your patience.

**Comment by lyn233** [comment]
您好 ， 我也填写了表单，daigl@。。。，还请尽快通过多谢！

**Comment by herobrine19** [comment]
您好 ， 我也填写了表单，还请尽快通过多谢！

**Comment by inamori1932** [comment]
您好，我也填写了表单，239...@qq.com，还请尽快通过。谢谢。
