### ISSUE TITLE
`Thought` field is empty

### ISSUE THREAD

**Issue by yc1999** [OpenBMB/ToolBench#67]
In your training dataset `toolllama_G123_dfs_train.json`, a lot of `Thought` field of the assistant is empty, what is the reason? (I'm afraid I've missed some important details.

**Comment by thuqinyj16** [comment]
Hi, thanks for your interest in this work! Some reasoning steps are way too easy, and does not need an explicit "thought" for reasoning. In such cases, the annotator (ChatGPT) would skip it. Only for those critical and difficult steps would the model generate the thought. In practice, this would also speed up the inference of our trained ToolLLaMA.

BTW, we can also provide a version that has a thought field for all steps (within a month).

**Comment by zengwang430521** [comment]
@thuqinyj16 

Hi, can you provide an early version of the data with thought field?

If the data processing is troublesome, can you provide the original data so that I can also process it by myself.

Looking for you response.
