### ISSUE TITLE
Internal Server Error when trying to send something to the assistant in the web ui. .env.local has been configured with appropriate keys and still nothing.

### ISSUE THREAD

**Issue by LiatHa** [OpenBMB/ToolBench#68]
C:\Droptop\AI\ToolBench\chatbot-ui-toolllama>npm run dev

> ai-chatbot-starter@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Droptop\AI\ToolBench\chatbot-ui-toolllama\.env.local
event - compiled client and server successfully in 5s (273 modules)
wait  - compiling...
event - compiled successfully in 299 ms (233 modules)
wait  - compiling /_error (client and server)...
wait  - compiling / (client and server)...
event - compiled client and server successfully in 20.7s (17741 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling /api/models (client and server)...
event - compiled successfully in 195 ms (41 modules)
wait  - compiling...
event - compiled successfully in 0 ms (41 modules)
wait  - compiling...
event - compiled successfully in 1 ms (41 modules)
wait  - compiling /api/chat (client and server)...
event - compiled successfully in 92 ms (44 modules)
 [TypeError: fetch failed] {
  cause:  [Error: connect ECONNREFUSED 127.0.0.1:5000] {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5000
}
}
 [TypeError: fetch failed] {
  cause:  [Error: connect ECONNREFUSED 127.0.0.1:5000] {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5000
}
}
 [TypeError: fetch failed] {
  cause:  [Error: connect ECONNREFUSED 127.0.0.1:5000] {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5000
}
}

the 3 different type errors are from three different tries to write something

**Comment by bill-deepmedia** [comment]
Hi! The frontend (written in Next.JS) includes apis that proxy requests to the Python backend, which runs the actual language model. Is it possible that the backend (the one that is run with toolbench_server.py and the arguments) is not running?

**Comment by lilbillybiscuit** [comment]
Hi! It seems that the connection is being refused on port 5000, which probably indicates that the backend service is not running. Note that the chatbot-ui-toolllama repository does not include the LLM code and makes requests to the Python backend. Could you try running the python backend via the file that says "toolbench_server.py"?
