### ISSUE TITLE
tooleval 测试文件不存在

### ISSUE THREAD

**Issue by gewenbin0992** [OpenBMB/ToolBench#71]
你好，感谢这项工作。

tooleval readme 中提到的文件：
data/answer/chatgpt_cot/G1_instruction
data/answer/toolllama_dfs/G1_instruction

没有传到data.zip里吗？可否提供下方便快速测试？
另外，已申请toolbench key，还未收到。

**Comment by pooruss** [comment]
您好，抱歉此前并未将相关文件上传，目前相关文件已上传到[reproduction_data.zip](https://drive.google.com/drive/folders/1yBUQ732mPu-KclJnuQELEhtKakdXFc3J)
另外方便提供一下您的邮箱或者麻烦您再填一份问卷吗，今天中午我们已经向已申请未发放的用户发放完毕，可能存在一些特殊情况导致您的邮箱无法正常收到我们的邮件

**Comment by gewenbin0992** [comment]
感谢回复。已重新提交问卷，邮箱为gewenbin0992@。。。
