### ISSUE TITLE
Understanding retrieval data formatting

### ISSUE THREAD

**Issue by AmenRa** [OpenBMB/ToolBench#73]
Hi, I do not understand how retrieval data are formatted.

The corpus contains `432799` lines, but only `10439` are unique.
Why are the corpus entries duplicated? Shouldn't be 16000+ unique lines/APIs?

There are `432394` lines in the train queries file, but only `87322` are unique.
There are `451` lines in the test queries file, but only `100` are unique.
I guess files containing queries are in this format to match the `qrels` files.
Am I right?

Thanks,

Elias

**Comment by Kunlun-Zhu** [comment]
You can refer to the section 2.2 of our paper about how we formulate the instructions data also used for the retriever experiments
[paper](https://arxiv.org/pdf/2307.16789.pdf)

**Comment by AmenRa** [comment]
Section 2.2 of the paper does not answer my question.
Could you please provide clarifications about data formatting?
Thank you.
