### ISSUE TITLE
是否可以不调用API

### ISSUE THREAD

**Issue by yamengxi** [OpenBMB/ToolBench#74]
我发现ToolBench的底层逻辑是通过与外部API交互得到信息，最终由大模型整合输出answer
但是，实验室服务器是内网环境，无法连接到外部API，请问在这种情况下，我能否不调用外部API得到大模型的回答？
（注：问题是简单问题，不需要使用tools工具。我希望对于这种简单问题，不与外部API交互就能直接得到模型输出answer）

**Comment by pooruss** [comment]
您好，目前我们的训练数据里没有涉及模型直接回答的数据，所以toolllama不会直接用自己的知识回答，而是总是会调用工具去作答～

**Comment by yamengxi** [comment]
感谢你的及时回复！我明白了，谢谢！
