### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by lyn233** [OpenBMB/ToolBench#75]
启动toolbench_server.py占用了大约38G显存，然后就OOM了。请问这个怎么解决呢？

![image](https://github.com/OpenBMB/ToolBench/assets/6488638/b7c1889e-8696-488d-802c-8b08c99c66b2)

**Comment by lyn233** [comment]
启动命令是 python toolbench/inference/toolbench_server.py     --tool_root_dir data/toolenv/tools/     --corpus_tsv_path data/retrieval/G1/corpus.tsv     --retrieval_model_path /data/gd/ToolLLaMA-7b     --retrieved_api_nums 5     --backbone_model toolllama     --model_path /data/gd/llama-7b     --max_observation_length 1024     --method DFS_woFilter_w2     --input_query_file data/instruction/inference_query_demo_open_domain.json     --output_answer_file data/answer/toolllama_lora_dfs_open_domain --rapidapi_key xxx

**Comment by pooruss** [comment]
您好，在open-domain setting下容易OOM，具体原因和修复见https://github.com/OpenBMB/ToolBench/issues/81
