### ISSUE TITLE
data/toolenv/tools/数据生成

### ISSUE THREAD

**Issue by huhy-uniplore** [OpenBMB/ToolBench#78]
您后，我想请问一下data/toolenv/tools/数据是怎么生成的？例如里面的每个api的json文件。

**Comment by pooruss** [comment]
您好，api的json文件是通过爬虫的方式从rapidapi上爬取得到；api.py代码文件是根据爬取的json文件，通过一系列规则自动生成。

**Comment by huhy-uniplore** [comment]
感谢您的回复。可以方便说一下你们的这一系列规则是什么呢？是用的什么脚本嘛？比如我要应用到自己的api上，我该怎么写出这些规则？

**Comment by camphora** [comment]
"api的json文件是通过爬虫的方式从rapidapi上爬取得到", 我理解这里所说的JSON文件就是tools 文件夹下面各个字文件夹内的json文件么？这里有考虑过将其转换成chatgpt functional call所接受的格式么？

**Comment by pooruss** [comment]
> 

是的，api的json就是tools 文件夹下面各个字文件夹内的json文件；

api json与function call json的转换可以参考这里 https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L185

**Comment by huhy-uniplore** [comment]
> > 
> 
> 是的，api的json就是tools 文件夹下面各个字文件夹内的json文件；
> 
> api json与function call json的转换可以参考这里 https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L185

请问一下，这里的json文件的生成，有没有相关脚本呢？和具体规则呢？

**Comment by camphora** [comment]
> 是的，api的json就是tools 文件夹下面各个字文件夹内的json文件；
> 
> api json与function call json的转换可以参考这里 https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L185

非常感谢您的回复，还想请问一下"api.py代码文件是根据爬取的json文件，通过一系列规则自动生成。" 这里所说的api.json 生成代码有相关参考么？
