### ISSUE TITLE
fix OOM with just one line of code

### ISSUE THREAD

**Issue by LinesHogan** [OpenBMB/ToolBench#81]
i have pull request with my fix.
OOM is because when we try to deepcopy child_io_state in DFS.py, we deepcopy its retriever as well. Adding `child_io_state.retriever=None` right after every `child_io_state = deepcopy(temp_now_node.io_state)` can solve OOM issue. If my PR haven't been accepted, you can follow my guide above to fix it.

**Comment by pooruss** [comment]
Thanks for reporting and fixing this issue!
