### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by ZhuomingL** [OpenBMB/ToolBench#83]
想请教一下。训练ToolLLaMa的数据集是通过处理data/answer/G1_answer的数据而来。但没理解answer/G1_answer中的数据是从哪里来，通过什么代码处理成G1_answer/xx_ChatGPT_DFS_woFilter_w2.json的格式。

**Comment by pooruss** [comment]
您好，可以参考 https://github.com/OpenBMB/ToolBench/issues/59 这里哈，如有进一步疑问或想法可以继续提出一起讨论～

**Comment by ZhuomingL** [comment]
> 您好，可以参考 #59 这里哈，如有进一步疑问或想法可以继续提出一起讨论～

明白了。感谢回复。
