### ISSUE TITLE
训练成本与训练时间

### ISSUE THREAD

**Issue by tro0o** [OpenBMB/ToolBench#84]
作者您好，请问按照您的训练参数对llama7B进行全量训练以及Lora训练时的显存占用以及训练时间分别是多少呢？是否测试过训练QLora版本呢？

**Comment by pooruss** [comment]
您好～
全参训练：batch size per device=2，gradient_accumulation_steps=2，num_train_epochs=2，gpus=4，显存占用60+g/gpu，训练时长约15小时；
LoRA训练：batch size per device=2，gradient_accumulation_steps=2，num_train_epochs=5，gpus=4，显存占用27+g/gpu，训练时长约30小时；

我们目前尚未支持QLora，欢迎一起合作共建！

**Comment by dyabel** [comment]
> 您好～ 全参训练：batch size per device=2，gradient_accumulation_steps=2，num_train_epochs=2，gpus=4，显存占用60+g/gpu，训练时长约15小时； LoRA训练：batch size per device=2，gradient_accumulation_steps=2，num_train_epochs=5，gpus=4，显存占用27+g/gpu，训练时长约30小时；
> 
> 我们目前尚未支持QLora，欢迎一起合作共建！

一张A100可以训吗
