### ISSUE TITLE
自定义api调用

### ISSUE THREAD

**Issue by ananwjq** [OpenBMB/ToolBench#85]
我按照readme里的hello world示例，进行自定义api的调用
不知道是我传参有问题吗，就是没法成功，运行脚本如下
```shell
export PYTHONPATH=./
export RAPIDAPI_KEY=""
 
python toolbench/inference/qa_pipeline.py \
    --tool_root_dir data/toolenv/tools/ \
    --backbone_model toolllama \
    --model_path ToolLLaMA_model/ToolLLaMA-2-7b \
    --max_observation_length 1024 \
    --observ_compress_method truncate \
    --method DFS_woFilter_w2 \
    --input_query_file data/instruction/hello.json \
    --output_answer_file data/answer/toolllama_dfs \
    --rapidapi_key $RAPIDAPI_KEY  \
    --use_rapidapi_key
``` 

结果如截图：
![image](https://github.com/OpenBMB/ToolBench/assets/113575763/5d143d76-3109-4178-a045-dfd2054a47d5)

我理解这种离线调用api，不需要请求rapidapi服务器吧，直接运行写好的那个函数结果当做接口返回，辛苦解答

**Comment by pooruss** [comment]
您好，可以对照您本地的代码与https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L345 此处的代码，检查代码是否一样且执行到这一行时的各个相关变量值

**Comment by ananwjq** [comment]
> 您好，可以对照您本地的代码与https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L345 此处的代码，检查代码是否一样且执行到这一行时的各个相关变量值

代码是一样的，RAPIDAPI_KEY 需要填吗，还是空着？

**Comment by mMrBun** [comment]
> > 您好，可以对照您本地的代码与https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L345 此处的代码，检查代码是否一样且执行到这一行时的各个相关变量值
> 
> 代码是一样的，RAPIDAPI_KEY 需要填吗，还是空着？

如果你不需要RAPIDAPI_KEY可以直接把上面作者给的连接代码中的判断去掉，类似下面这样，我也是这么做的，我这里多了一个tools_root参数是因为我把工具选择改到了接口内，这样我可以通过接口指定使用哪个目录下的tool，可以忽略😂
```python
                    payload = {
                        "category": self.cate_names[k],
                        "tool_name": self.tool_names[k],
                        "api_name": pure_api_name,
                        "tool_input": action_input,
                        "strip": self.observ_compress_method
                    }
                    if self.process_id == 0:
                        print(colored(f"query to {self.cate_names[k]}-->{self.tool_names[k]}-->{action_name}",
                                      color="yellow"))
                    response = get_rapidapi_response(payload, tools_root=self.tool_root_dir)
                    # 1 Hallucinating function names
```

**Comment by ananwjq** [comment]
解决了，应该是api.py里的函数需要toolbench_rapidapi_key这个参数，加上就好了

**Comment by pooruss** [comment]
感谢贡献！

之前的自定义api使用流程中对api.py函数的参数要求存在问题，我们已经更新了自定义api的脚本运行方法，添加了api_customization外置参数，避免了以上问题，如下：
```bash
export PYTHONPATH=./
python toolbench/inference/qa_pipeline.py \
    --tool_root_dir data/toolenv/tools/ \
    --backbone_model toolllama \
    --model_path ToolBench/ToolLLaMA-7b \
    --max_observation_length 1024 \
    --observ_compress_method truncate \
    --method DFS_woFilter_w2 \
    --input_query_file /path/to/your/query/file \
    --output_answer_file /path/to/your/output/file \
    --api_customization
```


> 解决了，应该是api.py里的函数需要toolbench_rapidapi_key这个参数，加上就好了
