### ISSUE TITLE
Inference stage， Always return You are not authorized for our rapidapi service. 

### ISSUE THREAD

**Issue by huxiaosheng123** [OpenBMB/ToolBench#86]
query to Weather-->the_weather_api-->weather_report_for_the_weather_api
Action Input: {
  "cityname": "New York"
}
Observation: {"error": "Unauthorized error...", "response": "You are not authorized for our rapidapi service. Please fill out our application form and we will process it as soon as possible."}

**Comment by jilianwang-meta** [comment]
Are you infering this model ? Can you tell me your GPU model and memory?

**Comment by pooruss** [comment]
Hi, have you applied for our toolbench key and do you use it properly during inference? It seems like your toolbench key can not be recognized by our server.
