### ISSUE TITLE
api info如何获取？

### ISSUE THREAD

**Issue by ddNTP** [OpenBMB/ToolBench#89]
![image](https://github.com/OpenBMB/ToolBench/assets/52226902/e49d8eaa-6bd2-43ce-a655-783a24ba8661)
我想使用rapid api中的其他api，但是我发现我无法获取这类json文件中的信息，尤其是api_list中的信息，能麻烦告诉一下在哪能找到这些信息吗？

**Comment by pooruss** [comment]
您好，以Sports/baseball.json这个api为例，在https://rapidapi.com/sparior/api/baseball4/这里可以找到api_list的所有信息

**Comment by pooruss** [comment]
您好，以Sports/baseball.json这个api为例，在 https://rapidapi.com/sparior/api/baseball4/ 这里可以找到api_list的所有信息
