### ISSUE TITLE
Adding API doesn't seem to work

### ISSUE THREAD

**Issue by MartSlaaf** [OpenBMB/ToolBench#90]
I added API exactly as per example, yet I have the response of model like this:

```
Thought:
Action: get_hello_world_for_hello_world
query to Customized-->hello_world-->get_hello_world_for_hello_world
Action Input: {}
Observation: {"error": "request invalid, data error. status_code=500", "response": ""}
```

It looks like it tries to get some info from remote, despite a completely locally defined API. How can I fix it?

**Comment by pooruss** [comment]
Hi, can you provide the bash command you used? To avoid getting the api response from our toolbench server, we need to pass the `--use_rapidapi_key`  and `--rapidapi_key ${rapidapi_key}` parameters in the command, like this:
```export RAPIDAPI_KEY=""
export PYTHONPATH=./
python toolbench/inference/qa_pipeline.py \
    --tool_root_dir data/toolenv/tools/ \
    --backbone_model toolllama \
    --model_path ToolBench/ToolLLaMA-7b \
    --max_observation_length 1024 \
    --observ_compress_method truncate \
    --method DFS_woFilter_w2 \
    --input_query_file /path/to/your/query/file \
    --output_answer_file /path/to/your/output/file \
    --rapidapi_key $RAPIDAPI_KEY \
    --use_rapidapi_key```

**Comment by lyn233** [comment]
您好 ，如果用server启动的化支持自定义api吗？

**Comment by MartSlaaf** [comment]
> Hi, can you provide the bash command you used? To avoid getting the api response from our toolbench server, we need to pass the `--use_rapidapi_key` and `--rapidapi_key ${rapidapi_key}` parameters in the command, like this:

Hello, thank you for your answer! I actually want a totally local example, as in your 'hello world' example. But as I dig through code, it looks like it will call for either one or another API server anyways. Can I at least use several?

**Comment by pooruss** [comment]
Hi, sorry for the late reply. Before we have some bugs in api customization. Now we believe that the bugs have been fixed and it should work now. Please try again and feel free to open this issue again!

**Comment by mattdeeperinsights** [comment]
Hi @MartSlaaf did you manage to get a custom tool running, if so could you share your code? I'm quite confused how to use this repo as there's no example code or notebooks

**Comment by MartSlaaf** [comment]
Hi @mattdeeperinsights,

I just modified the `rapidapi_wrapper` class at `inference/Downstream_tasks/rapidapi.py` to be able to execute my custom functions. This is a somewhat dirty hack, but it works.
Personally, I've started to replace it with my custom environment altogether, but yet again, very specialized one, not a general purpose.
