### ISSUE TITLE
license on rapid api description data

### ISSUE THREAD

**Issue by nlpcat** [OpenBMB/ToolBench#91]
would it be possible to change the license of crawled rapid api description data as Apache 2.0? is the full toolbench data CC BY NC 4.0 License due to chatGPT augmented part? thanks.

**Comment by thuqinyj16** [comment]
Yes, we've changed that, you can use it for commercial purposes.

**Comment by qmdnls** [comment]
Hi, could you clarify what you have changed? The README still says the data is released under CC BY NC 4.0 (i.e. non-commercial) licsense and the data releases don't seem to contain any further license information.
