### ISSUE TITLE
出现数组越界问题

### ISSUE THREAD

**Issue by qzDiao** [OpenBMB/ToolBench#92]
File "/ToolBench/toolbench/inference/toolbench_server.py", line 52, in run_pipeline
    self.pipeline.run_single_task(
  File "/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 517, in run_single_task
    [callback.on_request_end(
  File "/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 518, in <listcomp>
    chain=chain.terminal_node[0].messages,
IndexError: list index out of range

调用代码如下：
python toolbench/inference/toolbench_server.py \
    --tool_root_dir data/toolenv/tools/ \
    --corpus_tsv_path /ToolBench/data/retrieval/G1/corpus.tsv \
    --retrieval_model_path /ToolBench_IR_bert_based_uncased \
    --retrieved_api_nums 5 \
    --backbone_model toolllama \
    --model_path /ToolLLaMA-2-7b \
    --max_observation_length 1024 \
    --method DFS_woFilter_w2 \
    --input_query_file data/instruction/inference_query_demo_open_domain.json \
    --output_answer_file data/answer/toolllama_lora_dfs_open_domain \
    --toolbench_key $TOOLBENCH_KEY

**Comment by pooruss** [comment]
你好，可以提供下测试用例吗（query），我们需要先复现一下这个问题～

**Comment by acmisxuyutian** [comment]
> File "/ToolBench/toolbench/inference/toolbench_server.py", line 52, in run_pipeline self.pipeline.run_single_task( File "/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 517, in run_single_task [callback.on_request_end( File "/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 518, in chain=chain.terminal_node[0].messages, IndexError: list index out of range
> 
> 调用代码如下： python toolbench/inference/toolbench_server.py --tool_root_dir data/toolenv/tools/ --corpus_tsv_path /ToolBench/data/retrieval/G1/corpus.tsv --retrieval_model_path /ToolBench_IR_bert_based_uncased --retrieved_api_nums 5 --backbone_model toolllama --model_path /ToolLLaMA-2-7b --max_observation_length 1024 --method DFS_woFilter_w2 --input_query_file data/instruction/inference_query_demo_open_domain.json --output_answer_file data/answer/toolllama_lora_dfs_open_domain --toolbench_key $TOOLBENCH_KEY

![image](https://github.com/OpenBMB/ToolBench/assets/113601978/46898ebe-0892-4147-8f41-66db678abfd7)
这是因为非正常结束导致的端点节点列表为空。try一下就行了。
