### ISSUE TITLE
是否有支持的微信群？

### ISSUE THREAD

**Issue by brianhu2006** [OpenBMB/ToolBench#93]
discord 邀请link 不能work， 是否有支持的微信群？

**Comment by brianhu2006** [comment]
@pooruss  是否可以拉一个国内的微信群，大家一起讨论问题？

**Comment by pooruss** [comment]
你好，link已在readme中更新～目前暂时没有微信群，但discord里有中文频道方便大家讨论问题哈

**Comment by brianhu2006** [comment]
@pooruss Accessing Discord is quite challenging for me due to the reason that you are probably aware of - the VPN issue. I have to use a VPN service to bypass the firewall and connect to the Discord server, but sometimes the VPN is unstable or blocked. This makes it hard for me to communicate with my friends or join online communities on Discord.

**Comment by thuqinyj16** [comment]
You can also join 面壁智能's wechat / QQ group for more discussion~

**Comment by brianhu2006** [comment]
@thuqinyj16 提供以wechat id ？
