### ISSUE TITLE
能否提供一个如何构建的自己的API的toolbench的使用流程

### ISSUE THREAD

**Issue by brianhu2006** [OpenBMB/ToolBench#95]
我想要使用 toolbench 来调用我自己开发的 API，但是我对此一无所知。为了能够成功地使用 toolbench，我需要了解以下几个方面的内容：

1. 如何编写 seed instruction，即用自然语言描述 API 的功能和用法的指令。这些指令可以帮助 toolbench 生成更多的训练数据和测试用例。
2. 如何通过 GPT self instruction 生成更多训练数据，即用 GPT 模型根据 seed instruction 自动生成符合 API 规范的输入和输出数据。这些数据可以用来训练 API 的模型 retriever 和 toolllama。
3. 如何训练自己 API 的模型 retriever，即用训练数据中的输入作为查询，用输出作为答案，训练一个能够从 API 文档中检索相关信息的模型。这个模型可以帮助 toolbench 理解 API 的功能和参数。
4. 如何训练自己的 toolllama，即用训练数据中的输入和输出作为示例，训练一个能够根据用户的需求生成合适的 API 调用代码的模型。这个模型可以帮助 toolbench 为用户提供便捷的 API 使用体验。
5. 如何 inference 模型，即用测试数据中的输入作为查询，用模型 retriever 和 toolllama 生成相应的输出和代码，并与测试数据中的输出和代码进行比较，评估模型的准确性和效率。

如果有可能的话，也请提供一些示例代码或截图来说明每个步骤。这样我就可以更直观地学习和使用 toolbench 了。

**Comment by brianhu2006** [comment]
@pooruss 对于问题1 和2 有什么建议吗？

**Comment by pooruss** [comment]
您好：
1. seed instruction的构造方法可以参考我们的论文的附录；
2. “自动生成符合 API 规范的输入和输出数据”，您是指用gpt来生成API的返回吗？我们认为真实的API返回更合理，所有API返回都是实际调用API获取的
