### ISSUE TITLE
Thought message is empty

### ISSUE THREAD

**Issue by Hanqer** [OpenBMB/ToolBench#97]
In the multi-turns training data 'G123_dfs_train.json' almost all messages in assistant's reply, the 'Thought:' is empty? But in the system prompt, they instruct the model to thought about the current state, why?

**Comment by pooruss** [comment]
In the current data, only ~20% of thoughts are not empty and have content, due to inferior instruction following ability of chatgpt function call version when asking it to generate a thought in its response. 

We will update our data in a week, with more data and 90% of the data will have thought.

**Comment by Hanqer** [comment]
Thanks, look forward to the updated version.
