### ISSUE TITLE
关于使用davinci-003报错的问题

### ISSUE THREAD

**Issue by ZhuomingL** [OpenBMB/ToolBench#98]
试了一下运行davinci-003的话，代码报错。看代码逻辑，看上去也缺乏一些处理逻辑，请问运行davinci-003部分的代码是还没上传吗？
![image](https://github.com/OpenBMB/ToolBench/assets/33413087/93b367b9-fcdd-4b20-9118-caffda766026)
![image](https://github.com/OpenBMB/ToolBench/assets/33413087/6501f6a3-24c6-4c08-9c16-8b4241b7c796)

**Comment by pooruss** [comment]
你好，感谢指出问题，davinci代码已更新～

**Comment by ZhuomingL** [comment]
> 

不好意思哈，更新后执行python toolbench/inference/LLM/davinci_model.py 或者 上面的推理命令还是有点问题。
![image](https://github.com/OpenBMB/ToolBench/assets/33413087/3c9e52b4-ee22-4a47-bdab-3df4aeaee3f6)

**Comment by ZhuomingL** [comment]
你好，现在执行python toolbench/inference/LLM/davinci_model.py是可以正常运行的。但是执行python toolbench/inference/qa_pipeline.py还是会报错。

**Comment by ZhuomingL** [comment]
> 

![image](https://github.com/OpenBMB/ToolBench/assets/33413087/b97f6cb7-131b-4810-95ca-943e8e3e1803)

**Comment by ZhuomingL** [comment]
> 你好，现在执行python toolbench/inference/LLM/davinci_model.py是可以正常运行的。但是执行python toolbench/inference/qa_pipeline.py还是会报错。

不好意思，好像是我自己的问题。好像访问被openai拒了。
