### ISSUE TITLE
报错：ConnectTimeout

### ISSUE THREAD

**Issue by xxw19951018** [OpenBMB/ToolBench#99]
下面这行代码在运行时会出现ConnectTimeout的问题：
`response = requests.post("http://8.218.239.54:8080/rapidapi", json=payload, headers=headers, timeout=15)`

请问是什么原因？
8/30 Update
现在恢复了，请问这是什么原因导致的？

**Comment by pooruss** [comment]
您好，抱歉昨天服务器出现了问题导致无法访问，现在已经恢复了
